---
title: "Chem Hem and Micro Data Analysis"
output: html_document
---
```{r include = FALSE}
#Install packages only the first time you run the code
#install.packages("timeDate")
#install.packages("xlsx")
#install.packages("readxl")
#install.packages("dplyr")
#install.packages("reshape2")
#install.packages("knitr")
#install.packages("kableExtra")

#-------------------------------Required packages-------------------------------#

#Required packages: run these everytime you run the code
library(timeDate)
library(readxl)
library(dplyr)
library(lubridate)
library(reshape2)
library(knitr)
library(kableExtra)
```

```{r Determine date, echo = FALSE}
#-------------------------------holiday/weekend-------------------------------#

#Determine if yesterday was a holiday/weekend 

#get yesterday's DOW
# Yesterday_Day <- weekdays(as.Date(Sys.Date()-1))
Yest <- as.Date("11/25/2019", format = "%m/%d/%Y")
Yesterday_Day <- weekdays(Yest) #Rename as Yest_DOW
#Change the format for the date into timeDate format to be ready for the next function
Yesterday <- as.timeDate(Yest)

#get yesterday's DOW
Yesterday_Day <- dayOfWeek(Yesterday)

#Excludes Good Friday from the NYSE Holidays
NYSE_Holidays <- as.Date(holidayNYSE())
GoodFriday <- as.Date(GoodFriday())
MSHS_Holiday <- NYSE_Holidays[GoodFriday != NYSE_Holidays]

#This function determines whether yesterday was a holiday/weekend or no
Holiday_Det <- isHoliday(Yesterday, holidays = MSHS_Holiday)

#------------------------------Read Excel sheets------------------------------#
#The if-statement below helps in determining how many excel files are required

#-----------SCC Excel Files-----------#

if(((Holiday_Det) & (Yesterday_Day =="Mon"))|((Yesterday_Day =="Sun") & (isHoliday(Yesterday-(86400*2))))){
  SCC_Sunday <- read_excel(choose.files(caption = "Select SCC Sunday Report"), sheet = 1, col_names = TRUE)
  SCC_Saturday <- read_excel(choose.files(caption = "Select SCC Saturday Report"), sheet = 1, col_names = TRUE)
  #Merge the weekend data with the holiday data in one data frame
  SCC_Not_Weekday <- rbind(rbind(SCC_Holiday_Monday_or_Friday,SCC_Sunday),SCC_Saturday)
  SCC_Weekday <- read_excel(choose.files(caption = "Select SCC Weekday Report"), sheet = 1, col_names = TRUE)
} else if ((Holiday_Det) & (Yesterday_Day =="Sun")){
  SCC_Sunday <- read_excel(choose.files(caption = "Select SCC Sunday Report"), sheet = 1, col_names = TRUE)
  SCC_Saturday <- read_excel(choose.files(caption = "Select SCC Saturday Report"), sheet = 1, col_names = TRUE)
  #Merge the weekend data with the holiday data in one data frame
  SCC_Not_Weekday <- rbind(SCC_Sunday,SCC_Saturday)
  SCC_Weekday <- read_excel(choose.files(caption = "Select SCC Weekday Report"), sheet = 1, col_names = TRUE)
} else if ((Holiday_Det) & ((Yesterday_Day !="Mon")|(Yesterday_Day !="Sun"))){
  SCC_Holiday_Weekday <- read_excel(choose.files(caption = "Select SCC Holiday Report"), sheet = 1, col_names = TRUE)
  SCC_Not_Weekday <- SCC_Holiday_Weekday
  SCC_Weekday <- read_excel(choose.files(caption = "Select SCC Weekday Report"), sheet = 1, col_names = TRUE)
} else {
  SCC_Weekday <- read_excel(choose.files(caption = "Select SCC Weekday Report"), sheet = 1, col_names = TRUE)
}

#-----------SunQuest Excel Files-----------#

if(((Holiday_Det) & (Yesterday_Day =="Mon"))|((Yesterday_Day =="Sun") & (isHoliday(Yesterday-(86400*2))))){
  SQ_Holiday_Monday_or_Friday <- read_excel(choose.files(caption = "Select SunQuest Holiday Report"), sheet = 1, col_names = TRUE)
  SQ_Sunday <- read_excel(choose.files(caption = "Select SunQuest Sunday Report"), sheet = 1, col_names = TRUE)
  SQ_Saturday <- read_excel(choose.files(caption = "Select SunQuest Saturday Report"), sheet = 1, col_names = TRUE)
  #Merge the weekend data with the holiday data in one data frame
  SQ_Not_Weekday <- rbind(rbind(SQ_Holiday_Monday_or_Friday ,SQ_Sunday),SQ_Saturday)
  SQ_Weekday <- read_excel(choose.files(caption = "Select SunQuest Weekday Report"), sheet = 1, col_names = TRUE)
} else if ((Holiday_Det) & (Yesterday_Day =="Sun")){
  SQ_Sunday <- read_excel(choose.files(caption = "Select SunQuest Sunday Report"), sheet = 1, col_names = TRUE)
  SQ_Saturday <- read_excel(choose.files(caption = "Select SunQuest Saturday Report"), sheet = 1, col_names = TRUE)
  #Merge the weekend data with the holiday data in one data frame
  SQ_Not_Weekday <- rbind(SQ_Sunday,SQ_Saturday)
  SQ_Weekday <- read_excel(choose.files(caption = "Select SunQuest Weekday Report"), sheet = 1, col_names = TRUE)
} else if ((Holiday_Det) & ((Yesterday_Day !="Mon")|(Yesterday_Day !="Sunday"))){
  SQ_Holiday_Weekday <- read_excel(choose.files(caption = "Select SunQuest Holiday Report"), sheet = 1, col_names = TRUE)
  SQ_Not_Weekday <- SQ_Holiday_Weekday
  SQ_Weekday <- read_excel(choose.files(caption = "Select SunQuest Weekday Report"), sheet = 1, col_names = TRUE)
} else {
  SQ_Weekday <- read_excel(choose.files(caption = "Select SunQuest Weekday Report"), sheet = 1, col_names = TRUE)
}
```

```{r Reference Data, echo = FALSE}
# CP and Micro --------------------------------
# Import analysis reference data starting with test codes for SCC and Sunquest
reference_file <- "J:\\Presidents\\HSPI-PM\\Operations Analytics and Optimization\\Projects\\Service Lines\\Lab KPI\\Data\\Code Reference\\Analysis Reference 2019-12-02.xlsx"
test_code <- read_excel(reference_file, sheet = "TestNames")

tat_targets <- read_excel(reference_file, sheet = "Turnaround Targets")
tat_targets$Concate <- ifelse(tat_targets$Priority == "All" & tat_targets$`Pt Setting` == "All", tat_targets$Test,
                              ifelse(tat_targets$Priority != "All" & tat_targets$`Pt Setting` == "All", paste(tat_targets$Test, tat_targets$Priority),
                                     paste(tat_targets$Test, tat_targets$Priority, tat_targets$`Pt Setting`)))

scc_icu <- read_excel(reference_file, sheet = "SCC_ICU")
scc_setting <- read_excel(reference_file, sheet = "SCC_ClinicType")
sun_icu <- read_excel(reference_file, sheet = "SUN_ICU")
sun_setting <- read_excel(reference_file, sheet = "SUN_LocType")

mshs_site <- read_excel(reference_file, sheet = "SiteNames")

scc_wday <- SCC_Weekday
sun_wday <- SQ_Weekday

cp_micro_lab_order <- c("Troponin", "Lactate WB", "BUN", "HGB", "PT", "Rapid Flu", "C. diff")

site_order <- c("MSH", "MSQ", "MSBI", "MSB", "MSW", "MSSL")
pt_setting_order <- c("ED", "ICU", "IP Non-ICU", "Amb", "Other")
pt_setting_order2 <- c("ED & ICU", "IP Non-ICU", "Amb", "Other")

dashboard_priority_order <- c("AllSpecimen", "Stat", "Routine")
```

```{r Preprocessing Function, echo = FALSE}
preprocess_scc_sun <- function(raw_scc, raw_sun)  {
  # SCC DATA PROCESSING --------------------------
  # SCC lookup references ----------------------------------------------
  # Crosswalk labs included and remove out of scope labs
  raw_scc <- left_join(raw_scc, test_code[ , c("Test", "SCC_TestID", "Division")], by = c("TEST_ID" = "SCC_TestID"))
  raw_scc$TEST_ID <- as.factor(raw_scc$TEST_ID)
  raw_scc$Division <- as.factor(raw_scc$Division)
  raw_scc$TestIncl <- ifelse(is.na(raw_scc$Test), FALSE, TRUE)
  raw_scc <- raw_scc[raw_scc$TestIncl == TRUE, ]
  # Crosswalk units and identify ICUs
  raw_scc$WardandName <- paste(raw_scc$Ward, raw_scc$WARD_NAME)
  raw_scc <- left_join(raw_scc, scc_icu[ , c("Concatenate", "ICU")], by = c("WardandName" = "Concatenate"))
  raw_scc[is.na(raw_scc$ICU), "ICU"] <- FALSE
  # Crosswalk unit type
  raw_scc <- left_join(raw_scc, scc_setting, by = c("CLINIC_TYPE" = "Clinic_Type"))
  # Crosswalk site name
  raw_scc <- left_join(raw_scc, mshs_site, by = c("SITE" = "DataSite"))
  
  # SCC data formatting ----------------------------------------------
  raw_scc[c("Ward", "WARD_NAME", 
             "REQUESTING_DOC", 
             "GROUP_TEST_ID", "TEST_ID", "TEST_NAME", "PRIORITY", "Test",
             "COLLECT_CENTER_ID", "SITE", "Site",
             "CLINIC_TYPE", "Setting", "SettingRollUp")] <- lapply(raw_scc[c("Ward", "WARD_NAME", 
                                                                              "REQUESTING_DOC", 
                                                                              "GROUP_TEST_ID", "TEST_ID", "TEST_NAME", "PRIORITY", "Test",
                                                                              "COLLECT_CENTER_ID", "SITE", "Site",
                                                                              "CLINIC_TYPE", "Setting", "SettingRollUp")], as.factor)
  raw_scc[c("ORDERING_DATE", "COLLECTION_DATE", "RECEIVE_DATE", "VERIFIED_DATE")] <- lapply(raw_scc[c("ORDERING_DATE", "COLLECTION_DATE", "RECEIVE_DATE", "VERIFIED_DATE")],
                                                                                             as.POSIXlt, tz = "", format = "%Y-%m-%d %H:%M:%OS", options(digits.sec = 1))
  
  # Update patient setting to reflect ICU/Non-ICU and update priorities for ED and ICU labs
  raw_scc$MasterSetting <- ifelse(raw_scc$CLINIC_TYPE == "E", "ED", 
                                   ifelse(raw_scc$CLINIC_TYPE == "O", "Amb", 
                                          ifelse(raw_scc$CLINIC_TYPE == "I" & raw_scc$ICU == TRUE, "ICU", 
                                                 ifelse(raw_scc$CLINIC_TYPE == "I" & raw_scc$ICU != TRUE, "IP Non-ICU", "Other"))))
  raw_scc$DashboardSetting <- ifelse(raw_scc$MasterSetting == "ED" | raw_scc$MasterSetting == "ICU", "ED & ICU", raw_scc$MasterSetting)
  
  
  # Update priority to reflect ED/ICU as stat and create Master Priority for labs where all specimens are treated as stat
  raw_scc$AdjPriority <- ifelse(raw_scc$MasterSetting == "ED" | raw_scc$MasterSetting == "ICU" | raw_scc$PRIORITY == "S", "Stat", "Routine")
  raw_scc$DashboardPriority <- ifelse(tat_targets$Priority[match(raw_scc$Test, tat_targets$Test)] == "All", "AllSpecimen", raw_scc$AdjPriority)
  
  # Calculate turnaround times
  raw_scc$CollectToReceive <- raw_scc$RECEIVE_DATE - raw_scc$COLLECTION_DATE
  raw_scc$ReceiveToResult <- raw_scc$VERIFIED_DATE - raw_scc$RECEIVE_DATE
  raw_scc$CollectToResult <- raw_scc$VERIFIED_DATE - raw_scc$COLLECTION_DATE
  raw_scc[c("CollectToReceive", "ReceiveToResult", "CollectToResult")] <- lapply(raw_scc[c("CollectToReceive", "ReceiveToResult", "CollectToResult")], as.numeric, units = "mins")
  
  # Identify add on orders as orders placed more than 5 min after specimen received
  raw_scc$AddOnMaster <- ifelse(difftime(raw_scc$ORDERING_DATE, raw_scc$RECEIVE_DATE, units = "mins") > 5, "AddOn", "Original")
  
  # Identify specimens with missing collections times as those with collection time defaulted to receive time
  raw_scc$MissingCollect <- ifelse(raw_scc$CollectToReceive == 0, TRUE, FALSE)
  
  # Determine target TAT based on test, priority, and patient setting
  raw_scc$Concate1 <- paste(raw_scc$Test, raw_scc$DashboardPriority)
  raw_scc$Concate2 <- paste(raw_scc$Test, raw_scc$DashboardPriority, raw_scc$MasterSetting)
  
  raw_scc$ReceiveResultTarget <- ifelse(!is.na(match(raw_scc$Concate2, tat_targets$Concate)), tat_targets$ReceiveToResultTarget[match(raw_scc$Concate2, tat_targets$Concate)], 
                                         ifelse(!is.na(match(raw_scc$Concate1, tat_targets$Concate)), tat_targets$ReceiveToResultTarget[match(raw_scc$Concate1, tat_targets$Concate)],
                                                tat_targets$ReceiveToResultTarget[match(raw_scc$Test, tat_targets$Concate)]))
  
  raw_scc$CollectResultTarget <- ifelse(!is.na(match(raw_scc$Concate2, tat_targets$Concate)), tat_targets$CollectToResultTarget[match(raw_scc$Concate2, tat_targets$Concate)], 
                                         ifelse(!is.na(match(raw_scc$Concate1, tat_targets$Concate)), tat_targets$CollectToResultTarget[match(raw_scc$Concate1, tat_targets$Concate)],
                                                tat_targets$CollectToResultTarget[match(raw_scc$Test, tat_targets$Concate)]))
  
  raw_scc$ReceiveResultInTarget <- ifelse(raw_scc$ReceiveToResult <= raw_scc$ReceiveResultTarget, TRUE, FALSE)
  raw_scc$CollectResultInTarget <- ifelse(raw_scc$CollectToResult <= raw_scc$CollectResultTarget, TRUE, FALSE)
  
  # Identify and remove duplicate tests
  raw_scc$Concate3 <- paste(raw_scc$LAST_NAME, raw_scc$FIRST_NAME, 
                             raw_scc$ORDER_ID, raw_scc$TEST_NAME,
                             raw_scc$COLLECTION_DATE, raw_scc$RECEIVE_DATE, raw_scc$VERIFIED_DATE)
  
  raw_scc <- raw_scc[!duplicated(raw_scc$Concate3), ]
  
  # Identify which labs to include in TAT analysis
  # Exclude add on orders, orders from "other" settings, orders with collect or receive times after result, or orders with missing collect, receive, or result timestamps
  raw_scc$TATInclude <- ifelse(raw_scc$AddOnMaster != "Original" | raw_scc$MasterSetting == "Other" | raw_scc$CollectToResult < 0 | raw_scc$ReceiveToResult < 0 | is.na(raw_scc$CollectToResult) | is.na(raw_scc$ReceiveToResult), FALSE, TRUE)

  scc_master <- raw_scc[ , c("Ward", "WARD_NAME", "WardandName", 
                                   "ORDER_ID", "REQUESTING_DOC NAME", "MPI", "WORK SHIFT", 
                                   "TEST_NAME", "Test", "Division", "PRIORITY", 
                                   "Site", "ICU", "CLINIC_TYPE", 
                                   "Setting", "SettingRollUp", "MasterSetting", "DashboardSetting",
                                   "AdjPriority", "DashboardPriority", 
                                   "ORDERING_DATE", "COLLECTION_DATE", "RECEIVE_DATE", "VERIFIED_DATE", 
                                   "CollectToReceive", "ReceiveToResult", "CollectToResult", 
                                   "AddOnMaster", "MissingCollect", 
                                   "ReceiveResultTarget", "CollectResultTarget", 
                                   "ReceiveResultInTarget", "CollectResultInTarget", 
                                   "TATInclude")]
  colnames(scc_master) <- c("LocCode", "LocName", "LocConcat", 
                                 "OrderID", "RequestMD", "MSMRN", "WorkShift", 
                                 "TestName", "Test", "Division", "OrderPriority", 
                                 "Site", "ICU", "LocType", 
                                 "Setting", "SettingRollUp", "MasterSetting", "DashboardSetting",
                                 "AdjPriority", "DashboardPriority", 
                                 "OrderTime", "CollectTime", "ReceiveTime", "ResultTime", 
                                 "CollectToReceiveTAT", "ReceiveToResultTAT", "CollectToResultTAT", 
                                 "AddOnMaster", "MissingCollect", 
                                 "ReceiveResultTarget", "CollectResultTarget", 
                                 "ReceiveResultInTarget", "CollectResultInTarget", 
                                 "TATInclude")
  
  ## SUNQUEST DATA PROCESSING ----------
  # Sunquest lookup references ----------------------------------------------
  # Crosswalk labs included and remove out of scope labs
  raw_sun <- left_join(raw_sun, test_code[ , c("Test", "SUN_TestCode", "Division")], by = c("TestCode" = "SUN_TestCode"))
  raw_sun$TestCode <- as.factor(raw_sun$TestCode)
  raw_sun$Division <- as.factor(raw_sun$Division)
  raw_sun$TestIncl <- ifelse(is.na(raw_sun$Test), FALSE, TRUE)
  raw_sun <- raw_sun[raw_sun$TestIncl == TRUE, ]
  # Crosswalk units and identify ICUs
  raw_sun$LocandName <- paste(raw_sun$LocCode, raw_sun$LocName)
  raw_sun <- left_join(raw_sun, sun_icu[ , c("Concatenate", "ICU")], by = c("LocandName" = "Concatenate"))
  raw_sun[is.na(raw_sun$ICU), "ICU"] <- FALSE
  # Crosswalk unit type
  raw_sun <- left_join(raw_sun, sun_setting, by = c("LocType" = "LocType"))
  # Crosswalk site name
  raw_sun <- left_join(raw_sun, mshs_site, by = c("HospCode" = "DataSite"))
  
  # Sunquest data formatting --------------------------------------------
  raw_sun[c("HospCode", "BatTstCode", "BATName", "TestCode", "TSTName",
             "LocType", "LocCode", "LocName", 
             "SpecimenPriority", "PhysName", "SHIFT",
             "ReceiveTech", "ResultTech", "PerformingLabCode",
             "Test", "LocandName", "Setting", "SettingRollUp", "Site")] <- lapply(raw_sun[c("HospCode", "BatTstCode", "BATName", "TestCode", "TSTName",
                                                                                             "LocType", "LocCode", "LocName", 
                                                                                             "SpecimenPriority", "PhysName", "SHIFT",
                                                                                             "ReceiveTech", "ResultTech", "PerformingLabCode",
                                                                                             "Test", "LocandName", "Setting", "SettingRollUp", "Site")], as.factor)
  
  raw_sun[c("OrderDateTime", "CollectDateTime", "ReceiveDateTime", "ResultDateTime")] <- lapply(raw_sun[c("OrderDateTime", "CollectDateTime", "ReceiveDateTime", "ResultDateTime")], 
                                                                                                 as.POSIXlt, tz = "", format = "%m/%d/%Y %H:%M:%S")
  
  
  
  
  # Sunquest data preprocessing --------------------------------------------------
  # Update patient setting to reflect ICU/Non-ICU and update priorities for ED and ICU labs
  raw_sun$MasterSetting <- ifelse(raw_sun$SettingRollUp == "ED", "ED", 
                                   ifelse(raw_sun$SettingRollUp == "Amb", "Amb", 
                                          ifelse(raw_sun$SettingRollUp == "IP" & raw_sun$ICU == TRUE, "ICU",
                                                 ifelse(raw_sun$SettingRollUp == "IP" & raw_sun$ICU == FALSE, "IP Non-ICU", "Other"))))
  raw_sun$DashboardSetting <- ifelse(raw_sun$MasterSetting == "ED" | raw_sun$MasterSetting == "ICU", "ED & ICU", raw_sun$MasterSetting)
  
  # Update priority to reflect ED/ICU as stat and create Master Priority for labs where all specimens are treated as stat
  raw_sun$AdjPriority <- ifelse(raw_sun$MasterSetting != "ED" & raw_sun$MasterSetting != "ICU" & is.na(raw_sun$SpecimenPriority), "Routine",
                                 ifelse(raw_sun$MasterSetting == "ED" | raw_sun$MasterSetting == "ICU" | raw_sun$SpecimenPriority == "S", "Stat", "Routine"))
  raw_sun$DashboardPriority <- ifelse(tat_targets$Priority[match(raw_sun$Test, tat_targets$Test)] == "All", "AllSpecimen", raw_sun$AdjPriority)
  
  # Calculate turnaround times
  raw_sun$CollectToReceive <- raw_sun$ReceiveDateTime - raw_sun$CollectDateTime
  raw_sun$ReceiveToResult <- raw_sun$ResultDateTime - raw_sun$ReceiveDateTime
  raw_sun$CollectToResult <- raw_sun$ResultDateTime - raw_sun$CollectDateTime
  raw_sun[c("CollectToReceive", "ReceiveToResult", "CollectToResult")] <- lapply(raw_sun[c("CollectToReceive", "ReceiveToResult", "CollectToResult")], as.numeric, units = "mins")
  
  # Identify add on orders as orders placed more than 5 min after specimen received
  raw_sun$AddOnMaster <- ifelse(difftime(raw_sun$OrderDateTime, raw_sun$ReceiveDateTime, units = "mins") > 5, "AddOn", "Original")
  
  # Identify specimens with missing collections times as those with collection time defaulted to order time
  raw_sun$MissingCollect <- ifelse(raw_sun$CollectDateTime == raw_sun$OrderDateTime, TRUE, FALSE)
  
  # Determine target TAT based on test, priority, and patient setting
  raw_sun$Concate1 <- paste(raw_sun$Test, raw_sun$DashboardPriority)
  raw_sun$Concate2 <- paste(raw_sun$Test, raw_sun$DashboardPriority, raw_sun$MasterSetting)
  
  raw_sun$ReceiveResultTarget <- ifelse(!is.na(match(raw_sun$Concate2, tat_targets$Concate)), tat_targets$ReceiveToResultTarget[match(raw_sun$Concate2, tat_targets$Concate)], 
                                         ifelse(!is.na(match(raw_sun$Concate1, tat_targets$Concate)), tat_targets$ReceiveToResultTarget[match(raw_sun$Concate1, tat_targets$Concate)],
                                                tat_targets$ReceiveToResultTarget[match(raw_sun$Test, tat_targets$Concate)]))
  
  raw_sun$CollectResultTarget <- ifelse(!is.na(match(raw_sun$Concate2, tat_targets$Concate)), tat_targets$CollectToResultTarget[match(raw_sun$Concate2, tat_targets$Concate)], 
                                         ifelse(!is.na(match(raw_sun$Concate1, tat_targets$Concate)), tat_targets$CollectToResultTarget[match(raw_sun$Concate1, tat_targets$Concate)],
                                                tat_targets$CollectToResultTarget[match(raw_sun$Test, tat_targets$Concate)]))
  
  raw_sun$ReceiveResultInTarget <- ifelse(raw_sun$ReceiveToResult <= raw_sun$ReceiveResultTarget, TRUE, FALSE)
  raw_sun$CollectResultInTarget <- ifelse(raw_sun$CollectToResult <= raw_sun$CollectResultTarget, TRUE, FALSE)
  
  # Identify and remove duplicate tests
  raw_sun$Concate3 <- paste(raw_sun$PtNumber, 
                             raw_sun$HISOrderNumber, raw_sun$TSTName,
                             raw_sun$CollectDateTime, raw_sun$ReceiveDateTime, raw_sun$ResultDateTime)
  
  raw_sun <- raw_sun[!duplicated(raw_sun$Concate3), ]
  
  
  
  # Identify which labs to include in TAT analysis
  # Exclude add on orders, orders from "other" settings, orders with collect or receive times after result, or orders with missing collect, receive, or result timestamps
  raw_sun$TATInclude <- ifelse(raw_sun$AddOnMaster != "Original" | raw_sun$MasterSetting == "Other" | raw_sun$CollectToResult < 0 | raw_sun$ReceiveToResult < 0 | is.na(raw_sun$CollectToResult) | is.na(raw_sun$ReceiveToResult), FALSE, TRUE)
  
  sun_master <- raw_sun[ ,c("LocCode", "LocName", "LocandName", 
                                  "HISOrderNumber", "PhysName", "PtNumber", "SHIFT",            
                                  "TSTName", "Test", "Division", "SpecimenPriority", 
                                  "Site", "ICU", "LocType",               
                                  "Setting", "SettingRollUp", "MasterSetting", "DashboardSetting", 
                                  "AdjPriority", "DashboardPriority", 
                                  "OrderDateTime", "CollectDateTime", "ReceiveDateTime", "ResultDateTime", 
                                  "CollecttoReceive", "ReceivetoResult", "CollecttoResult", 
                                  "AddOnMaster", "MissingCollect", 
                                  "ReceiveResultTarget", "CollectResultTarget", 
                                  "ReceiveResultInTarget", "CollectResultInTarget", 
                                  "TATInclude")]
  
  colnames(sun_master) <- c("LocCode", "LocName", "LocConcat", 
                                 "OrderID", "RequestMD", "MSMRN", "WorkShift", 
                                 "TestName", "Test", "Division", "OrderPriority", 
                                 "Site", "ICU", "LocType", 
                                 "Setting", "SettingRollUp", "MasterSetting", "DashboardSetting", 
                                 "AdjPriority", "DashboardPriority", 
                                 "OrderTime", "CollectTime", "ReceiveTime", "ResultTime", 
                                 "CollectToReceiveTAT", "ReceiveToResultTAT", "CollectToResultTAT", 
                                 "AddOnMaster", "MissingCollect", 
                                 "ReceiveResultTarget", "CollectResultTarget", 
                                 "ReceiveResultInTarget", "CollectResultInTarget", 
                                 "TATInclude")
  
  
  scc_sun_master <- rbind(scc_master, sun_master)
  
  scc_sun_master[c("LocConcat", "RequestMD", "WorkShift", "AdjPriority", "AddOnMaster")] <-
    lapply(scc_sun_master[c("LocConcat", "RequestMD", "WorkShift", "AdjPriority", "AddOnMaster")], as.factor)
  
  scc_sun_master$Site <- factor(scc_sun_master$Site, levels = site_order)
  scc_sun_master$Test <- factor(scc_sun_master$Test, levels = cp_micro_lab_order)
  scc_sun_master$MasterSetting <- factor(scc_sun_master$MasterSetting, levels = pt_setting_order)
  scc_sun_master$DashboardSetting <- factor(scc_sun_master$DashboardSetting, levels = pt_setting_order2)
  scc_sun_master$DashboardPriority <- factor(scc_sun_master$DashboardPriority, levels = dashboard_priority_order)
  
  scc_sun_list <- list(raw_scc, raw_sun, scc_sun_master)
  
}
```

```{r Dashboard Generation, echo = FALSE}
scc_sun_wday_list <- preprocess_scc_sun(SCC_Weekday, SQ_Weekday)
scc_wday <- scc_sun_wday_list[[1]]
sun_wday <- scc_sun_wday_list[[2]]
scc_sun_wday_master <- scc_sun_wday_list[[3]]

# Manipulate and reshape SCC and Sunquest data -----------------------------------------------
# Start summarizing data
chemistry <- scc_sun_wday_master[scc_sun_wday_master$Division == "Chemistry" & scc_sun_wday_master$TATInclude == TRUE, ] %>%
  group_by(Test, Site, DashboardPriority, DashboardSetting) %>%
  summarize(ResultedVolume = n(), ReceiveResultInTarget = sum(ReceiveResultInTarget), CollectResultInTarget = sum(CollectResultInTarget),
            ReceiveResultPercent = round(ReceiveResultInTarget/ResultedVolume, digits = 3)*100, CollectResultPercent = round(CollectResultInTarget/ResultedVolume, digits = 3)*100)

chemistry_dashboard <- melt(chemistry, id.var = c("Test", "Site", "DashboardPriority", "DashboardSetting"), measure.vars = c("ReceiveResultPercent", "CollectResultPercent"))

chemistry_dashboard_2 <- chemistry_dashboard %>%
  mutate(value = cell_spec(value, "html", color = ifelse(is.na(value), "black", 
                                                         ifelse(value >= 90.0, "green",
                                                                ifelse(value >=80.0 &  value < 90.0, "yellow", "red")))))
chemistry_dashboard_2$value <- paste0(chemistry_dashboard_2$value, "%")

chemistry_summary <- dcast(chemistry_dashboard_2, Test + DashboardPriority + DashboardSetting ~ variable + Site, value.var = "value")

chemistry_summary %>%
  kable(format = "html", escape = FALSE, align = "c") %>%
  kable_styling(bootstrap_options = "striped")
```

```{r Additional table, echo = FALSE}
  
hematology <- scc_sun_wday_master[scc_sun_wday_master$Division == "Hematology" & scc_sun_wday_master$TATInclude == TRUE, ] %>%
  group_by(Test, Site, DashboardPriority, DashboardSetting) %>%
  summarize(ResultedVolume = n(), ReceiveResultInTarget = sum(ReceiveResultInTarget), CollectResultInTarget = sum(CollectResultInTarget),
            ReceiveResultPercent = round(ReceiveResultInTarget/ResultedVolume, digits = 3)*100, CollectResultPercent = round(CollectResultInTarget/ResultedVolume, digits = 3)*100)

hematology_table <- melt(hematology, id.var = c("Test", "Site", "DashboardPriority", "DashboardSetting"), measure.vars = c("ResultedVolume", "ReceiveResultInTarget", "CollectResultInTarget", "ReceiveResultPercent", "CollectResultPercent"))

hematology_table2 <- dcast(hematology_table, Test + DashboardPriority + DashboardSetting ~ variable + Site, value.var = "value")

hematology_dashboard <- melt(hematology, id.var = c("Test", "Site", "DashboardPriority", "DashboardSetting"), measure.vars = c("ReceiveResultPercent", "CollectResultPercent"))
hematology_summary <- dcast(hematology_dashboard, Test + DashboardPriority + DashboardSetting ~ variable + Site, value.var = "value")

micro <- scc_sun_wday_master[scc_sun_wday_master$Division == "Microbiology RRL" & scc_sun_wday_master$TATInclude == TRUE, ] %>%
  group_by(Test, Site, DashboardPriority, DashboardSetting) %>%
  summarize(ResultedVolume = n(), ReceiveResultInTarget = sum(ReceiveResultInTarget), CollectResultInTarget = sum(CollectResultInTarget),
            ReceiveResultPercent = round(ReceiveResultInTarget/ResultedVolume, digits = 3)*100, CollectResultPercent = round(CollectResultInTarget/ResultedVolume, digits = 3)*100)

micro_table <- melt(micro, id.var = c("Test", "Site", "DashboardPriority", "DashboardSetting"), value.var = c("ResultedVolume", "ReceiveResultInTarget", "CollectResultInTarget", "ReceiveResultPercent", "CollectResultPercent"))

micro_table2 <- dcast(micro_table, Test + DashboardPriority + DashboardSetting ~ variable + Site, value.var = "value")

micro_dashboard <- melt(micro, id.var = c("Test", "Site", "DashboardPriority", "DashboardSetting"), measure.vars = c("ReceiveResultPercent", "CollectResultPercent"))
micro_dashboard <- micro_dashboard[!(micro_dashboard$Test == "C. diff" & micro_dashboard$DashboardSetting == "Amb"), ]

micro_summary <- dcast(micro_dashboard, Test + DashboardPriority + DashboardSetting ~ variable + Site, value.var = "value")
micro_summary[micro_summary$Test == "Rapid Flu" & micro_summary$DashboardSetting == "Amb", ]

micro_volume <- melt(micro, id.var = c("Test", "Site", "DashboardPriority", "DashboardSetting"), measure.vars = c("ResultedVolume"))
micro_volume <- dcast(micro_volume, Test + DashboardPriority + DashboardSetting ~ variable + Site)

# # Determine percentage of labs with missing collection times -------------------------------
missing_collect <- scc_sun_wday_master %>%
  group_by(Site) %>%
  summarize(ResultedVolume = n(), MissingCollection = sum(MissingCollect, na.rm = TRUE), Percent = round(MissingCollection/ResultedVolume*100, digits = 1))

missing_collect_table <- dcast(missing_collect, "Percent Specimens Missing Collection" ~ Site, value.var = "Percent")

# Determine number of add-on orders stratified by test and site ------------------------------
add_on_volume <- scc_sun_wday_master %>%
  group_by(Test, Site) %>%
  summarize(AddOnVolume = sum(AddOnMaster == "AddOn", na.rm = TRUE))

add_on_table <- dcast(add_on_volume, Test ~ Site, value.var = "AddOnVolume")
```

