---
title: "MSHS Laboratory KPI Dashboard"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---


```{r include = FALSE}
#Install packages only the first time you run the code
# install.packages("timeDate")
# install.packages("lubridate")
# install.packages("readxl")
# install.packages("dplyr")
# install.packages("reshape2")
# install.packages("knitr")
# install.packages("gdtools")
# install.packages("kableExtra")
# install.packages("formattable")
# install.packages("bizdays")
# install.packages("rmarkdown")
# install.packages("stringr")
# install.packages("writexl")

#-------------------------------Required packages------------------------------#

#Required packages: run these every time you run the code
library(timeDate)
library(readxl)
library(bizdays)
library(dplyr)
library(lubridate)
library(reshape2)
library(knitr)
# library(gdtools)
library(kableExtra)
library(formattable)
library(rmarkdown)
library(stringr)
library(writexl)


```


<h4><span style = "color:red">Draft - Not For Distribution</h4></span style = "color:red">


```{r global_options, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r Determine date, warning = FALSE, message = FALSE, echo = FALSE}
#Clear existing history
rm(list = ls())
#-------------------------------holiday/weekend-------------------------------#
# Get today and yesterday's date

Today <- as.timeDate(format(Sys.Date(), "%m/%d/%Y"))
# Today <- as.timeDate(as.Date("12/10/2020", format = "%m/%d/%Y"))


#Determine if yesterday was a holiday/weekend
#get yesterday's DOW
Yesterday <- as.timeDate(format(Sys.Date() - 1, "%m/%d/%Y"))
# Yesterday <- as.timeDate(as.Date("12/9/2020", format = "%m/%d/%Y"))

#Get yesterday's DOW
Yesterday_Day <- dayOfWeek(Yesterday)

#Remove Good Friday from MSHS Holidays
NYSE_Holidays <- as.Date(holidayNYSE(year = 1990:2100))
GoodFriday <- as.Date(GoodFriday())
MSHS_Holiday <- NYSE_Holidays[GoodFriday != NYSE_Holidays]

#Determine whether yesterday was a holiday/weekend
Holiday_Det <- isHoliday(Yesterday, holidays = MSHS_Holiday)

#Set up a calendar for collect to received TAT calculations for Path & Cyto
create.calendar("MSHS_working_days", MSHS_Holiday,
                weekdays = c("saturday", "sunday"))
bizdays.options$set(default.calendar = "MSHS_working_days")
```

#### *Dashboard Creation Date: `r format(Today, "%m/%d/%Y")`*

```{r Import all data, warning = FALSE, message = FALSE, echo = FALSE}
# Select file/folder path for easier file selection and navigation
# user_wd <- choose.dir(caption = "Select your working directory")
#user_wd <- "J:\\deans\\Presidents\\HSPI-PM\\Operations Analytics and Optimization\\Projects\\Service Lines\\Lab KPI\\Data"
#user_path <- paste0(user_wd, "\\*.*")

if (list.files("J://") == "Presidents") {
  user_directory <- paste0("J:/Presidents/HSPI-PM/",
                           "Operations Analytics and Optimization/Projects/",
                           "Service Lines/Lab Kpi/Data")
} else {
  user_directory <- paste0("J:/deans/Presidents/HSPI-PM/",
                           "Operations Analytics and Optimization/Projects/", 
                           "Service Lines/Lab Kpi/Data")
}
user_path <- paste0(user_directory, "/*.*")


#------------------------------Read Excel sheets------------------------------#

# The if-statement below determines the number of raw data files to import
# based on the day of week and holidays. The user is then prompted to select
# each file from the relevant folder.

if (((Holiday_Det) & (Yesterday_Day == "Mon")) |
   ((Yesterday_Day == "Sun") & (isHoliday(Yesterday - (86400*2))))) { 
  # Scenario 1: Mon Holiday or Friday Holiday (Need to select 4 files)
  # Save scenario
  scenario <- 1
  # Import SCC data
  SCC_Holiday_Monday_or_Friday <- read_excel(
    choose.files(default = paste0(user_directory, "/SCC CP Reports/*.*"), 
                 caption = "Select SCC Report for Labs Resulted on 
                 Recent Holiday"), 
    sheet = 1, col_names = TRUE)
  SCC_Sunday <- read_excel(
    choose.files(default = paste0(user_directory, "/SCC CP Reports/*.*"), 
                 caption = "Select SCC Report for Labs Resulted on Sunday"), 
    sheet = 1, col_names = TRUE)
  SCC_Saturday <- read_excel(
    choose.files(default = paste0(user_directory, "/SCC CP Reports/*.*"), 
                 caption = "Select SCC Report for Labs Resulted on Saturday"), 
    sheet = 1, col_names = TRUE)
  #Merge the weekend data with the holiday data in one data frame
  SCC_Not_Weekday <- rbind(SCC_Holiday_Monday_or_Friday, 
                           SCC_Sunday, 
                           SCC_Saturday)
  SCC_Weekday <- read_excel(
    choose.files(default = paste0(user_directory, "/SCC CP Reports/*.*"), 
                 caption = "Select SCC Report for Labs Resulted on 
                 Most Recent Weekday"), 
    sheet = 1, col_names = TRUE)
  # 
  # Import Sunquest data
  SQ_Holiday_Monday_or_Friday <- suppressWarnings(read_excel(
    choose.files(default = paste0(user_directory, "/SUN CP Reports/*.*"), 
                 caption = "Select Sunquest Report for Labs Resulted 
                 on Recent Holiday"), 
    sheet = 1, col_names = TRUE))
  SQ_Sunday <- suppressWarnings(read_excel(
    choose.files(default = paste0(user_directory, "/SUN CP Reports/*.*"), 
                 caption = "Select Sunquest Report for Labs Resulted 
                 on Sunday"), 
    sheet = 1, col_names = TRUE))
  SQ_Saturday <- suppressWarnings(read_excel(
    choose.files(default = paste0(user_directory, "/SUN CP Reports/*.*"), 
                 caption = "Select Sunquest Report for Labs Resulted 
                 on Saturday"), 
    sheet = 1, col_names = TRUE))
  #Merge the weekend data with the holiday data in one data frame
  SQ_Not_Weekday <- rbind(SQ_Holiday_Monday_or_Friday, SQ_Sunday, SQ_Saturday)
  SQ_Weekday <- suppressWarnings(read_excel(
    choose.files(default = paste0(user_directory, "/SUN CP Reports/*.*"), 
                 caption = "Select Sunquest Report for Labs Resulted 
                 on Most Recent Weekday"), 
    sheet = 1, col_names = TRUE))
  # #
  # # Import Powerpath data
  # PP_Holiday_Monday_or_Friday <- read_excel(
  #   choose.files(default = paste0(user_directory, 
  #                                 "/AP & Cytology Signed Cases Reports/*.*"), 
  #                caption = "Select PowerPath Report for Specimens Signed Out 
  #                on Recent Holiday"), 
  #   skip = 1, 1)
  # PP_Holiday_Monday_or_Friday  <- PP_Holiday_Monday_or_Friday[
  #   -nrow(PP_Holiday_Monday_or_Friday), ]
  # PP_Sunday <- read_excel(
  #   choose.files(default = paste0(user_directory,
  #                                 "/AP & Cytology Signed Cases Reports/*.*"), 
  #                caption = "Select PowerPath Report for Specimens Signed Out 
  #                on Sunday"), 
  #   skip = 1, 1)
  # PP_Sunday <- PP_Sunday[-nrow(PP_Sunday), ]
  # PP_Saturday <- read_excel(
  #   choose.files(default = paste0(user_directory, 
  #                                 "/AP & Cytology Signed Cases Reports/*.*"), 
  #                caption = "Select PowerPath Report for Specimens Signed Out 
  #                on Saturday"), 
  #   skip = 1, 1)
  # PP_Saturday <- PP_Saturday[-nrow(PP_Saturday), ]
  # #Merge the weekend data with the holiday data in one data frame
  # PP_Not_Weekday <- data.frame(rbind(PP_Holiday_Monday_or_Friday, 
  #                                    PP_Sunday, 
  #                                    PP_Saturday), stringsAsFactors = FALSE)
  # PP_Weekday <- read_excel(
  #   choose.files(default = paste0(user_directory, 
  #                                 "/AP & Cytology Signed Cases Reports/*.*"),
  #                caption = "Select PowerPath Report for Specimens Signed Out 
  #                on Most Recent Weekday"),
  #   skip = 1, 1)
  # PP_Weekday <- data.frame(PP_Weekday[-nrow(PP_Weekday), ], 
  #                          stringsAsFactors = FALSE)
  # #
  # # Import EPIC Cytology data
  # Epic_Holiday_Monday_or_Friday <- read_excel(
  #   choose.files(default = paste0(user_directory, "/EPIC Cytology/*.*"), 
  #                caption = "Select Epic Report for Specimens Signed Out 
  #                on Recent Holiday"), 1)
  # Epic_Sunday <- read_excel(
  #   choose.files(default = paste0(user_directory, "/EPIC Cytology/*.*"), 
  #                caption = "Select Epic Report for Specimens Signed Out 
  #                on Sunday"), 1)
  # Epic_Saturday <- read_excel(
  #   choose.files(default = paste0(user_directory, "/EPIC Cytology/*.*"), 
  #                caption = "Select PowerPath Report for Specimens Signed Out 
  #                on Saturday"), 1)
  # #Merge the weekend data with the holiday data in one data frame
  # Epic_Not_Weekday <- data.frame(rbind(Epic_Holiday_Monday_or_Friday, 
  #                                      Epic_Sunday, 
  #                                      Epic_Saturday),stringsAsFactors = FALSE)
  # Epic_Weekday <- read_excel(
  #   choose.files(default = paste0(user_directory, "/EPIC Cytology/*.*"), 
  #                caption = "Select Epic Report for Specimens Signed Out 
  #                on Most Recent Weekday"), 1)
} else if ((Holiday_Det) & (Yesterday_Day == "Sun")){
  # Scenario 2: Regular Monday (Need to select 3 files)
  # Save scenario
  scenario <- 2
  #
  # Import SCC data
  SCC_Sunday <- read_excel(
    choose.files(default = paste0(user_directory, "/SCC CP Reports/*.*"), 
                 caption = "Select SCC Report for Labs Resulted on Sunday"), 
    sheet = 1, col_names = TRUE)
  SCC_Saturday <- read_excel(
    choose.files(default = paste0(user_directory, "/SCC CP Reports/*.*"), 
                 caption = "Select SCC Report for Labs Resulted on Saturday"), 
    sheet = 1, col_names = TRUE)
  #Merge the weekend data with the holiday data in one data frame
  SCC_Not_Weekday <- rbind(SCC_Sunday, SCC_Saturday)
  SCC_Weekday <- read_excel(
    choose.files(default = paste0(user_directory, "/SCC CP Reports/*.*"), 
                 caption = "Select SCC Report for Labs Resulted 
                 on Most Recent Weekday"), 
    sheet = 1, col_names = TRUE)
  #
  # Import Sunquest data
  SQ_Sunday <- suppressWarnings(read_excel(
    choose.files(default = paste0(user_directory, "/SUN CP Reports/*.*"), 
                 caption = "Select Sunquest Report for Labs Resulted 
                 on Sunday"), 
    sheet = 1, col_names = TRUE))
  SQ_Saturday <- suppressWarnings(read_excel(
    choose.files(default = paste0(user_directory, "/SUN CP Reports/*.*"), 
                 caption = "Select Sunquest Report for Labs Resulted 
                 on Saturday"), 
    sheet = 1, col_names = TRUE))
  #Merge the weekend data with the holiday data in one data frame
  SQ_Not_Weekday <- rbind(SQ_Sunday,SQ_Saturday)
  SQ_Weekday <- suppressWarnings(read_excel(
    choose.files(default = paste0(user_directory, "/SUN CP Reports/*.*"), 
                 caption = "Select Sunquest Report for Labs Resulted 
                 on Most Recent Weekday"), 
    sheet = 1, col_names = TRUE))
  #
  # # Import Powerpath data
  # PP_Sunday <- read_excel(
  #   choose.files(default = paste0(user_directory, 
  #                                 "/AP & Cytology Signed Cases Reports/*.*"), 
  #                caption = "Select PowerPath Report for Specimens Signed Out 
  #                on Sunday"), 
  #   skip = 1, 1)
  # PP_Sunday <- PP_Sunday[-nrow(PP_Sunday), ]
  # PP_Saturday <- read_excel(
  #   choose.files(default = paste0(user_directory,
  #                                 "/AP & Cytology Signed Cases Reports/*.*"), 
  #                caption = "Select PowerPath Report for Specimens Signed Out 
  #                on Saturday"),
  #   skip = 1, 1)
  # PP_Saturday <- PP_Saturday[-nrow(PP_Saturday), ]
  # #Merge the weekend data with the holiday data in one data frame
  # PP_Not_Weekday <- data.frame(rbind(PP_Sunday, 
  #                                    PP_Saturday), stringsAsFactors = FALSE)
  # PP_Weekday <- read_excel(
  #   choose.files(default = paste0(user_directory, 
  #                                 "/AP & Cytology Signed Cases Reports/*.*"), 
  #                caption = "Select PowerPath Report for Specimens Signed Out 
  #                on Most Recent Weekday"), 
  #   skip = 1, 1)
  # PP_Weekday <- data.frame(PP_Weekday[-nrow(PP_Weekday), ], 
  #                          stringsAsFactors = FALSE)
  # #
  # # Import Epic Cytology data
  # Epic_Sunday <- read_excel(
  #   choose.files(default = paste0(user_directory, "/EPIC Cytology/*.*"), 
  #                caption = "Select Epic Report for Specimens Signed Out 
  #                on Sunday"), 
  #   1)
  # Epic_Saturday <- read_excel(
  #   choose.files(default = paste0(user_directory, "/EPIC Cytology/*.*"), 
  #                caption = "Select Epic Report for Specimens Signed Out 
  #                on Saturday"), 
  #   1)
  # #Merge the weekend data with the holiday data in one data frame
  # Epic_Not_Weekday <- data.frame(rbind(Epic_Sunday, 
  #                                      Epic_Saturday), 
  #                                stringsAsFactors = FALSE)
  # Epic_Weekday <- read_excel(
  #   choose.files(default = paste0(user_directory, "/EPIC Cytology/*.*"), 
  #                caption = "Select Epic Report for Specimens Signed Out 
  #                on Most Recent Weekday"), 
  #   1)
} else if ((Holiday_Det) & ((Yesterday_Day != "Mon") | 
                            (Yesterday_Day != "Sun"))){ 
  #Scenario 3: Midweek holiday (Need to select 2 files)
  # Save scenario
  scenario <- 3
  #
  # Import SCC data
  SCC_Holiday_Weekday <- read_excel(
    choose.files(default = paste0(user_directory, "/SCC CP Reports/*.*"), 
                 caption = "Select SCC Report for Labs Resulted 
                 on Recent Holiday"), 
    sheet = 1, col_names = TRUE)
  SCC_Not_Weekday <- SCC_Holiday_Weekday
  SCC_Weekday <- read_excel(
    choose.files(default = paste0(user_directory, "/SCC CP Reports/*.*"), 
                 caption = "Select SCC Report for Labs Resulted 
                 on Most Recent Weekday"), 
    sheet = 1, col_names = TRUE)
  #
  # Import Sunquest data
  SQ_Holiday_Weekday <- suppressWarnings(read_excel(
    choose.files(default = paste0(user_directory, "/SUN CP Reports/*.*"), 
                 caption = "Select Sunquest Report for Labs Resulted 
                 on Recent Holiday"), 
    sheet = 1, col_names = TRUE))
  SQ_Not_Weekday <- SQ_Holiday_Weekday
  SQ_Weekday <- suppressWarnings(read_excel(
    choose.files(default = paste0(user_directory, "/SUN CP Reports/*.*"), 
                 caption = "Select Sunquest Report for Labs Resulted 
                 on Most Recent Weekday"), 
    sheet = 1, col_names = TRUE))
  #
  # # Import Powerpath data
  # PP_Holiday_Weekday <- read_excel(
  #   choose.files(default = paste0(user_directory, 
  #                                 "/AP & Cytology Signed Cases Reports/*.*"), 
  #                caption = "Select PowerPath Report for Specimens Signed Out 
  #                on Recent Holiday"), 
  #   skip = 1, 1)
  # PP_Holiday_Weekday <- PP_Holiday_Weekday[-nrow(PP_Holiday_Weekday), ]
  # PP_Not_Weekday <- data.frame(PP_Holiday_Weekday, stringsAsFactors = FALSE)
  # PP_Weekday <- read_excel(
  #   choose.files(default = paste0(user_directory, 
  #                                 "/AP & Cytology Signed Cases Reports/*.*"), 
  #                caption = "Select PowerPath Report for Specimens Signed Out 
  #                on Most Recent Weekday"), 
  #   skip = 1, 1)
  # PP_Weekday <- data.frame(PP_Weekday[-nrow(PP_Weekday), ], 
  #                          stringsAsFactors = FALSE)
  # #
  # # Import Powerpath data
  # Epic_Holiday_Weekday <- read_excel(
  #   choose.files(default = paste0(user_directory, "/EPIC Cytology/*.*"), 
  #                caption = "Select Epic Report for Specimens Signed Out 
  #                on Recent Holiday"), 
  #   1)
  # Epic_Not_Weekday <- data.frame(Epic_Holiday_Weekday, stringsAsFactors = FALSE)
  # Epic_Weekday <- read_excel(
  #   choose.files(default = paste0(user_directory, "/EPIC Cytology/*.*"), 
  #                caption = "Select Epic Report for Specimens Signed Out 
  #                on Most Recent Weekday"), 
  #   1)
} else { #Scenario 4: Tue-Fri without holidays (Need to select 1 file)
  # Save scenario
  scenario <- 4
  #
  # Import SCC data
  SCC_Weekday <- read_excel(
    choose.files(default = paste0(user_directory, "/SCC CP Reports/*.*"), 
                 caption = "Select SCC Report for Labs Resulted 
                 on Most Recent Weekday"), 
    sheet = 1, col_names = TRUE)
  SCC_Not_Weekday <- NULL
  #
  # Import Sunquest data
  SQ_Weekday <- suppressWarnings(read_excel(
    choose.files(default = paste0(user_directory, "/SUN CP Reports/*.*"), 
                 caption = "Select SunQuest Report for Labs Resulted 
                 n Most Recent Weekday"), 
    sheet = 1, col_names = TRUE))
  SQ_Not_Weekday <- NULL
  #
  # # Import Powerpath data
  # PP_Weekday <- read_excel(
  #   choose.files(default = paste0(user_directory, 
  #                                 "/AP & Cytology Signed Cases Reports/*.*"), 
  #                caption = "Select PowerPath Report for Specimens Signed Out 
  #                on Most Recent Weekday"), 
  #   skip = 1, 1)
  # PP_Weekday <- data.frame(PP_Weekday[-nrow(PP_Weekday), ], 
  #                          stringsAsFactors = FALSE)
  # PP_Not_Weekday <- NULL
  # #
  # # Import Epic Cytology data
  # Epic_Weekday <- read_excel(
  #   choose.files(default = paste0(user_directory, "/EPIC Cytology/*.*"), 
  #                caption = "Select Epic Report for Specimens Signed Out 
  #                on Most Recent Weekday"), 
  #   1)
  # Epic_Not_Weekday <- NULL
}

# #-----------Cytology Backlog Excel Files-----------#
# #For the backlog files the read excel is starting from the second row and remove last row
# Cytology_Backlog_Raw <- read_excel(
#   choose.files(default = paste0(user_directory, 
#                                 "/Cytology Backlog Reports/*.*"), 
#                caption = "Select Cytology Backlog Report"), 
#   skip =1, 1)
# Cytology_Backlog_Raw <- data.frame(
#   Cytology_Backlog_Raw[-nrow(Cytology_Backlog_Raw), ], stringsAsFactors = FALSE)
```

```{r Reference Data, warning = FALSE, message = FALSE, echo = FALSE}
# CP and Micro --------------------------------
# Import analysis reference data starting with test codes for SCC and Sunquest
reference_file <- choose.files(
  default = paste0(user_directory, "/Code Reference/*.*"), 
  caption = "Select analysis reference file")

test_code <- read_excel(reference_file, sheet = "TestNames")

tat_targets <- read_excel(reference_file, sheet = "Turnaround Targets")
tat_targets$Concate <- ifelse(tat_targets$Priority == "All" & 
                                tat_targets$`Pt Setting` == "All", 
                              tat_targets$Test,
                              ifelse(tat_targets$Priority != "All" & 
                                       tat_targets$`Pt Setting` == "All", 
                                     paste(tat_targets$Test, 
                                           tat_targets$Priority),
                                     paste(tat_targets$Test, 
                                           tat_targets$Priority, 
                                           tat_targets$`Pt Setting`)))

scc_icu <- read_excel(reference_file, sheet = "SCC_ICU")
scc_setting <- read_excel(reference_file, sheet = "SCC_ClinicType")
sun_icu <- read_excel(reference_file, sheet = "SUN_ICU")
sun_setting <- read_excel(reference_file, sheet = "SUN_LocType")

mshs_site <- read_excel(reference_file, sheet = "SiteNames")

scc_wday <- SCC_Weekday
sun_wday <- SQ_Weekday

cp_micro_lab_order <- c("Troponin", "Lactate WB", "BUN", "HGB", "PT", "Rapid Flu", "C. diff")

site_order <- c("MSH", "MSQ", "MSBI", "MSB", "MSW", "MSM", "MSSN")
city_sites <- c("MSH", "MSQ", "MSBI", "MSB", "MSW", "MSM")

pt_setting_order <- c("ED", "ICU", "IP Non-ICU", "Amb", "Other")
pt_setting_order2 <- c("ED & ICU", "IP Non-ICU", "Amb", "Other")
dashboard_pt_setting <- c("ED & ICU", "IP Non-ICU", "Amb")

dashboard_priority_order <- c("All", "Stat", "Routine")

# # To Be Updated in Analysis reference file
# #-----------Patient Setting Excel File-----------#
# #Using Rev Center to determine patient setting
# Patient_Setting <- data.frame(read_excel(reference_file, 
#                                          sheet = "AP_Patient Setting"), 
#                               stringsAsFactors = FALSE)
# 
# #-----------Anatomic Pathology Targets Excel File-----------#
# TAT_Targets <- data.frame(read_excel(reference_file, 
#                                      sheet = "AP_TAT Targets"), 
#                           stringsAsFactors = FALSE)
# 
# #-----------GI Codes Excel File-----------#
# #Upload the exclusion vs inclusion criteria associated with the GI codes
# GI_Codes <- data.frame(read_excel(reference_file, sheet = "GI_Codes"), 
#                        stringsAsFactors = FALSE)
# 
# #-----------Create table template for Cyto/Path-----------#
# 
# #Cyto
# Table_Template_Cyto <- data.frame(matrix(ncol=19, nrow = 4))
# colnames(Table_Template_Cyto) <- c("spec_group", "Patient.Setting",
#                                    "No_Cases_Signed", 
#                                    "MSH.x", "BIMC.x", "MSQ.x","NYEE.x", 
#                                    "PACC.x", "R.x", "SL.x", "KH.x", "BIMC.y", 
#                                    "MSH.y", "MSQ.y", "NYEE.y", "PACC.y", "R.y", 
#                                    "SL.y", "KH.y")
# Table_Template_Cyto[1] <- c('CYTO GYN','CYTO GYN','CYTO NONGYN', 'CYTO NONGYN')
# Table_Template_Cyto[2] <- c('IP', 'Amb')
# 
# Table_Template_Cyto_V2 <- data.frame(matrix(ncol=12, nrow = 4))
# colnames(Table_Template_Cyto_V2) <- c("spec_group", "Patient.Setting",
#                                       "No_Cases_Signed", 
#                                       "Received_to_Signed_Out_within_target", 
#                                       "BIMC", "MSH", "MSQ", "NYEE", "PACC", 
#                                       "R", "SL", "KH")
# Table_Template_Cyto_V2[1] <- c('CYTO GYN', 'CYTO GYN', 
#                                'CYTO NONGYN', 'CYTO NONGYN')
# Table_Template_Cyto_V2[2] <- c('IP', 'Amb')
# 
# Table_Template_Cyto_Vol <- data.frame(matrix(ncol=10, nrow = 4))
# colnames(Table_Template_Cyto_Vol) <- c("spec_group", "Patient.Setting", 
#                                        "BIMC", "MSH", "MSQ", "NYEE", "PACC", 
#                                        "R", "SL", "KH")
# Table_Template_Cyto_Vol[1] <- c('CYTO GYN', 'CYTO GYN', 
#                                 'CYTO NONGYN', 'CYTO NONGYN')
# Table_Template_Cyto_Vol[2] <- c('IP', 'Amb')
# 
# #Patho
# Table_Template_Patho <- data.frame(matrix(ncol=17, nrow = 4))
# colnames(Table_Template_Patho) <- c("spec_group", "Patient.Setting", 
#                                     "No_Cases_Signed", 
#                                     "MSH.x", "BIMC.x", "MSQ.x", "PACC.x", 
#                                     "R.x", "SL.x", "KH.x", "BIMC.y", "MSH.y", 
#                                     "MSQ.y", "PACC.y", "R.y", "SL.y", "KH.y")
# Table_Template_Patho[1] <- c('Breast', 'Breast', 'GI', 'GI')
# Table_Template_Patho[2] <- c('IP', 'Amb')
# 
# Table_Template_Patho_Vol <- data.frame(matrix(ncol=9, nrow = 4))
# colnames(Table_Template_Patho_Vol) <- c("spec_group", "Patient.Setting", 
#                                         "BIMC", "MSH", "MSQ", "PACC", 
#                                         "R", "SL", "KH")
# Table_Template_Patho_Vol[1] <- c('Breast', 'Breast', 'GI', 'GI')
# Table_Template_Patho_Vol[2] <- c('IP', 'Amb')
```


```{r Original Custom Function for preprocessing raw SCC and Sunquest data, warning = FALSE, message = FALSE, echo = FALSE}
preprocess_scc_sun <- function(raw_scc, raw_sun)  {
 
# SCC DATA PROCESSING --------------------------
  # SCC lookup references ----------------------------------------------
  # Crosswalk labs included and remove out of scope labs
  raw_scc <- left_join(raw_scc, 
                       test_code[ , c("Test", "SCC_TestID", "Division")], 
                       by = c("TEST_ID" = "SCC_TestID"))
  raw_scc$TEST_ID <- as.factor(raw_scc$TEST_ID)
  raw_scc$Division <- as.factor(raw_scc$Division)

  raw_scc <- raw_scc %>%
    mutate(TestIncl = ifelse(is.na(raw_scc$Test), FALSE, TRUE))
  
  raw_scc <- raw_scc %>%
    filter(TestIncl)
  
  # Crosswalk units and identify ICUs
  raw_scc <- raw_scc %>%
    mutate(WardandName = paste(Ward, WARD_NAME))
  
  raw_scc <- left_join(raw_scc, scc_icu[ , c("Concatenate", "ICU")], 
                       by = c("WardandName" = "Concatenate"))
  raw_scc[is.na(raw_scc$ICU), "ICU"] <- FALSE
  
  # Crosswalk unit type
  raw_scc <- left_join(raw_scc, scc_setting, 
                       by = c("CLINIC_TYPE" = "Clinic_Type"))
  # Crosswalk site name
  raw_scc <- left_join(raw_scc, mshs_site, 
                       by = c("SITE" = "DataSite"))
  
  # SCC data formatting ----------------------------------------------
  raw_scc[c("Ward", 
            "WARD_NAME", 
            "REQUESTING_DOC",
            "GROUP_TEST_ID",
            "TEST_ID",
            "TEST_NAME",
            "Test",
            "COLLECT_CENTER_ID",
            "SITE",
            "Site",
            "CLINIC_TYPE",
            "Setting",
            "SettingRollUp")] <- lapply(raw_scc[c("Ward",
                                                  "WARD_NAME",
                                                  "REQUESTING_DOC", 
                                                  "GROUP_TEST_ID",
                                                  "TEST_ID", 
                                                  "TEST_NAME", 
                                                  "Test",
                                                  "COLLECT_CENTER_ID",
                                                  "SITE",
                                                  "Site",
                                                  "CLINIC_TYPE",
                                                  "Setting",
                                                  "SettingRollUp")], 
                                        as.factor)
  
  # Fix any timestamps that weren't imported correctly and then format as date/time
  raw_scc[c("ORDERING_DATE", 
            "COLLECTION_DATE", 
            "RECEIVE_DATE", 
            "VERIFIED_DATE")] <- lapply(raw_scc[c("ORDERING_DATE", 
                                                  "COLLECTION_DATE", 
                                                  "RECEIVE_DATE", 
                                                  "VERIFIED_DATE")], 
           function(x) ifelse(!is.na(x) & str_detect(x, "\\*.*\\*")  == TRUE, 
                              str_replace(x, "\\*.*\\*", ""), x))
  
  raw_scc[c("ORDERING_DATE",
            "COLLECTION_DATE",
            "RECEIVE_DATE",
            "VERIFIED_DATE")] <- lapply(raw_scc[c("ORDERING_DATE",
                                                  "COLLECTION_DATE",
                                                  "RECEIVE_DATE",
                                                  "VERIFIED_DATE")], 
           as.POSIXct, tz = "UTC", format = "%Y-%m-%d %H:%M:%OS", 
           options(digits.sec = 1))
  
  # Add a column for Resulted date for later use in repository
  raw_scc <- raw_scc %>%
    mutate(ResultedDate = as.Date(VERIFIED_DATE, format = "%m/%d/%Y"))
  
  # Update patient setting to reflect ICU/Non-ICU and 
  # update priorities for ED and ICU labs
  raw_scc <- raw_scc %>%
    mutate(MasterSetting = ifelse(CLINIC_TYPE == "E", "ED", 
                                  ifelse(CLINIC_TYPE == "O", "Amb", 
                                         ifelse(CLINIC_TYPE == "I" & 
                                                  ICU == TRUE, "ICU",
                                                ifelse(CLINIC_TYPE == "I" & 
                                                         ICU != TRUE, 
                                                       "IP Non-ICU", 
                                                       "Other")))),
           DashboardSetting = ifelse(MasterSetting == "ED" | 
                                       MasterSetting == "ICU", "ED & ICU", 
                                     MasterSetting))
  
  # Update priority to reflect ED/ICU as stat and create Master Priority 
  # for labs where all specimens are treated as stat
  raw_scc <- raw_scc %>%
    mutate(AdjPriority = ifelse(MasterSetting == "ED" | 
                                  MasterSetting == "ICU" | PRIORITY == "S", 
                                "Stat", "Routine"),
           DashboardPriority = ifelse(
             tat_targets$Priority[match(Test, tat_targets$Test)] == "All", 
                                      "All", AdjPriority))

  # Calculate turnaround times
  raw_scc <- raw_scc %>%
    mutate(CollectToReceive = RECEIVE_DATE - COLLECTION_DATE,
           ReceiveToResult = VERIFIED_DATE - RECEIVE_DATE,
           CollectToResult = VERIFIED_DATE - COLLECTION_DATE)
  
  raw_scc[c("CollectToReceive", "ReceiveToResult", "CollectToResult")] <- 
    lapply(raw_scc[c("CollectToReceive", "ReceiveToResult", "CollectToResult")], 
           as.numeric, units = "mins")
  
  # Identify add on orders as orders placed more than 5 min 
  # after specimen received
  # Identify specimens with missing collections times as those with 
  # collection time defaulted to receive time
  raw_scc <- raw_scc %>%
    mutate(AddOnMaster = ifelse(difftime(ORDERING_DATE, 
                                         RECEIVE_DATE, units = "mins") > 5, 
                                "AddOn", "Original"),
           MissingCollect = ifelse(CollectToReceive == 0, TRUE, FALSE))
  
  # Determine target TAT based on test, priority, and patient setting
  raw_scc <- raw_scc %>%
    mutate(Concate1 = paste(Test, DashboardPriority),
           Concate2 = paste(Test, DashboardPriority, MasterSetting),
           ReceiveResultTarget = ifelse(
             !is.na(match(Concate2, tat_targets$Concate)),
             tat_targets$ReceiveToResultTarget[match(Concate2, 
                                                     tat_targets$Concate)],
             ifelse(!is.na(match(Concate1, tat_targets$Concate)), 
                    tat_targets$ReceiveToResultTarget[match(Concate1, 
                                                            tat_targets$Concate)],
                    tat_targets$ReceiveToResultTarget[match(Test, 
                                                            tat_targets$Concate)])),
           CollectResultTarget = ifelse(
             !is.na(match(Concate2, tat_targets$Concate)),
             tat_targets$CollectToResultTarget[match(Concate2, 
                                                     tat_targets$Concate)], 
             ifelse(!is.na(match(Concate1, tat_targets$Concate)), 
                    tat_targets$CollectToResultTarget[match(Concate1, 
                                                            tat_targets$Concate)], 
                    tat_targets$CollectToResultTarget[match(Test, 
                                                            tat_targets$Concate)])),
           ReceiveResultInTarget = ReceiveToResult <= ReceiveResultTarget, 
           CollectResultInTarget = CollectToResult <= CollectResultTarget)
  
  # Identify and remove duplicate tests
  raw_scc <- raw_scc %>%
    mutate(Concate3 = paste(LAST_NAME, FIRST_NAME,
                            ORDER_ID, TEST_NAME, 
                            COLLECTION_DATE, RECEIVE_DATE, VERIFIED_DATE))
  
  raw_scc <- raw_scc[!duplicated(raw_scc$Concate3), ]
  
  # Identify which labs to include in TAT analysis
  # Exclude add on orders, orders from "other" settings, orders with collect or 
  # receive times after result, or orders with missing collect, receive, or 
  # result timestamps
  raw_scc <- raw_scc %>% 
    mutate(TATInclude = ifelse(AddOnMaster != "Original" | 
                                 MasterSetting == "Other" | 
                                 CollectToResult < 0 | 
                                 ReceiveToResult < 0 | 
                                 is.na(CollectToResult) | 
                                 is.na(ReceiveToResult), FALSE, TRUE))

  scc_master <- raw_scc[ , c("Ward", "WARD_NAME", "WardandName",
                             "ORDER_ID", "REQUESTING_DOC NAME", 
                             "MPI", "WORK SHIFT",
                             "TEST_NAME", "Test", "Division", "PRIORITY", 
                             "Site", "ICU", "CLINIC_TYPE", 
                             "Setting", "SettingRollUp", 
                             "MasterSetting", "DashboardSetting",
                             "AdjPriority", "DashboardPriority",
                             "ORDERING_DATE", "COLLECTION_DATE", 
                             "RECEIVE_DATE", "VERIFIED_DATE",
                             "ResultedDate", 
                             "CollectToReceive", "ReceiveToResult", 
                             "CollectToResult", 
                             "AddOnMaster", "MissingCollect", 
                             "ReceiveResultTarget", "CollectResultTarget", 
                             "ReceiveResultInTarget", "CollectResultInTarget", 
                             "TATInclude")]
  
  colnames(scc_master) <- c("LocCode", "LocName", "LocConcat",
                            "OrderID", "RequestMD", 
                            "MSMRN", "WorkShift", 
                            "TestName", "Test", "Division", "OrderPriority", 
                            "Site", "ICU", "LocType", 
                            "Setting", "SettingRollUp", 
                            "MasterSetting", "DashboardSetting",
                            "AdjPriority", "DashboardPriority",
                            "OrderTime", "CollectTime", 
                            "ReceiveTime", "ResultTime", 
                            "ResultDate", 
                            "CollectToReceiveTAT", "ReceiveToResultTAT", 
                            "CollectToResultTAT", 
                            "AddOnMaster", "MissingCollect", 
                            "ReceiveResultTarget", "CollectResultTarget", 
                            "ReceiveResultInTarget", "CollectResultInTarget", 
                            "TATInclude")

  
  ## SUNQUEST DATA PROCESSING ----------
  # Sunquest lookup references ----------------------------------------------
  # Crosswalk labs included and remove out of scope labs
  raw_sun <- left_join(raw_sun, test_code[ , c("Test", 
                                               "SUN_TestCode", 
                                               "Division")], 
                       by = c("TestCode" = "SUN_TestCode"))
  raw_sun$TestCode <- as.factor(raw_sun$TestCode)
  raw_sun$Division <- as.factor(raw_sun$Division)
  raw_sun <- raw_sun %>%
    mutate(TestIncl = ifelse(is.na(Test), FALSE, TRUE))
  
  raw_sun <- raw_sun[raw_sun$TestIncl == TRUE, ]
  
  # Crosswalk units and identify ICUs
  raw_sun <- raw_sun %>%
    mutate(LocandName = paste(LocCode, LocName))
  
  raw_sun <- left_join(raw_sun, sun_icu[ , c("Concatenate", "ICU")], 
                       by = c("LocandName" = "Concatenate"))
  raw_sun[is.na(raw_sun$ICU), "ICU"] <- FALSE
  
  # Crosswalk unit type
  raw_sun <- left_join(raw_sun, sun_setting, by = c("LocType" = "LocType"))
  
  # Crosswalk site name
  raw_sun <- left_join(raw_sun, mshs_site, by = c("HospCode" = "DataSite"))
  #Asala Added this to tackle the issue of the other site temporarly until Kate comes back
  # raw_sun <- inner_join(raw_sun, mshs_site, by = c("HospCode" = "DataSite"))

  # Sunquest data formatting --------------------------------------------
  raw_sun[c("HospCode", "BatTstCode", "BATName", "TestCode", "TSTName",
             "LocType", "LocCode", "LocName", 
             "PhysName", "SHIFT",
             "ReceiveTech", "ResultTech", "PerformingLabCode",
             "Test", "LocandName", "Setting", "SettingRollUp", "Site")] <- 
    lapply(raw_sun[c("HospCode", "BatTstCode", "BATName", "TestCode", "TSTName",
                     "LocType", "LocCode", "LocName", 
                     "PhysName", "SHIFT", 
                     "ReceiveTech", "ResultTech", "PerformingLabCode", 
                     "Test", "LocandName", "Setting", "SettingRollUp", "Site")],
           as.factor)
  
  # Fix any timestamps that weren't imported correctly and then format as date/time
  raw_sun[c("OrderDateTime", 
            "CollectDateTime", 
            "ReceiveDateTime", 
            "ResultDateTime")] <- 
    lapply(raw_sun[c("OrderDateTime", 
                     "CollectDateTime", 
                     "ReceiveDateTime", 
                     "ResultDateTime")], 
           function(x) ifelse(!is.na(x) & str_detect(x, "\\*.*\\*")  == TRUE, 
                              str_replace(x, "\\*.*\\*", ""), x))

  raw_sun[c("OrderDateTime", 
            "CollectDateTime", 
            "ReceiveDateTime", 
            "ResultDateTime")] <- 
    lapply(raw_sun[c("OrderDateTime", 
                     "CollectDateTime", 
                     "ReceiveDateTime", 
                     "ResultDateTime")], 
           as.POSIXct, tz = "UTC", format = "%m/%d/%Y %H:%M:%S")
  
  # Add a column for Resulted date for later use in repository
  raw_sun <- raw_sun %>%
    mutate(ResultedDate = as.Date(ResultDateTime, format = "%m/%d/%Y"))

  # Sunquest data preprocessing -----------------------------------------------
  # Update patient setting to reflect ICU/Non-ICU and update priorities for 
  # ED and ICU labs
  raw_sun <- raw_sun %>%
    mutate(MasterSetting = ifelse(SettingRollUp == "ED", "ED", 
                                  ifelse(SettingRollUp == "Amb", "Amb", 
                                         ifelse(SettingRollUp == "IP" & 
                                                  ICU == TRUE, "ICU",
                                                ifelse(SettingRollUp == "IP" & 
                                                         ICU == FALSE, 
                                                       "IP Non-ICU", "Other")))), 
           DashboardSetting = ifelse(MasterSetting == "ED" | 
                                       MasterSetting == "ICU", "ED & ICU", 
                                     MasterSetting))
  
  # Update priority to reflect ED/ICU as stat and create Master Priority for 
  # labs where all specimens are treated as stat
  raw_sun <- raw_sun %>%
    mutate(AdjPriority = ifelse(MasterSetting != "ED" & MasterSetting != "ICU" &
                                  is.na(SpecimenPriority), "Routine",
                                ifelse(MasterSetting == "ED" | 
                                         MasterSetting == "ICU" | 
                                         SpecimenPriority == "S", "Stat", 
                                       "Routine")),
           DashboardPriority = ifelse(tat_targets$Priority[match(
             Test, tat_targets$Test)] == "All", "All", AdjPriority))

  # Calculate turnaround times
  raw_sun <- raw_sun %>%
    mutate(CollectToReceive = ReceiveDateTime - CollectDateTime,
           ReceiveToResult = ResultDateTime - ReceiveDateTime,
           CollectToResult = ResultDateTime - CollectDateTime)
  
  raw_sun[c("CollectToReceive", "ReceiveToResult", "CollectToResult")] <- 
    lapply(raw_sun[c("CollectToReceive", "ReceiveToResult", "CollectToResult")], 
           as.numeric, units = "mins")
  
  # Identify add on orders as orders placed more than 5 min after 
  # specimen received. 
  # Identify specimens with missing collections times as those with collection 
  # time defaulted to order time
  raw_sun <- raw_sun %>%
    mutate(AddOnMaster = ifelse(difftime(OrderDateTime, ReceiveDateTime, 
                                         units = "mins") > 5, "AddOn", 
                                "Original"),
           MissingCollect = ifelse(CollectDateTime == OrderDateTime, TRUE, 
                                   FALSE))
  
  # Determine target TAT based on test, priority, and patient setting
  raw_sun <- raw_sun %>%
    mutate(Concate1 = paste(Test, DashboardPriority), 
           Concate2 = paste(Test, DashboardPriority, MasterSetting),
           ReceiveResultTarget = ifelse(!is.na(match(Concate2, 
                                                     tat_targets$Concate)), 
                                        tat_targets$ReceiveToResultTarget[
                                          match(Concate2, tat_targets$Concate)], 
                                        ifelse(!is.na(match(Concate1,
                                                            tat_targets$Concate)),
                                               tat_targets$ReceiveToResultTarget[
                                                 match(Concate1, 
                                                       tat_targets$Concate)],
                                               tat_targets$ReceiveToResultTarget[
                                                 match(Test, 
                                                       tat_targets$Concate)])),
           CollectResultTarget = ifelse(!is.na(match(Concate2, 
                                                     tat_targets$Concate)), 
                                        tat_targets$CollectToResultTarget[
                                          match(Concate2, tat_targets$Concate)], 
                                        ifelse(!is.na(match(Concate1, 
                                                            tat_targets$Concate)), 
                                               tat_targets$CollectToResultTarget[
                                                 match(Concate1, 
                                                       tat_targets$Concate)], 
                                               tat_targets$CollectToResultTarget[
                                                 match(Test, 
                                                       tat_targets$Concate)])),
           ReceiveResultInTarget = ReceiveToResult <= ReceiveResultTarget,
           CollectResultInTarget = CollectToResult <= CollectResultTarget)
  
  # Identify and remove duplicate tests
  raw_sun <- raw_sun %>%
    mutate(Concate3 = paste(PtNumber, HISOrderNumber, TSTName, 
                            CollectDateTime, ReceiveDateTime, ResultDateTime))
  
  raw_sun <- raw_sun[!duplicated(raw_sun$Concate3), ]
  
  # Identify which labs to include in TAT analysis
  # Exclude add on orders, orders from "other" settings, orders with collect or 
  # receive times after result, or orders with missing collect, receive, or 
  # result timestamps
  raw_sun <- raw_sun %>%
    mutate(TATInclude = ifelse(AddOnMaster != "Original" | 
                                 MasterSetting == "Other" | 
                                 CollectToResult < 0 | 
                                 ReceiveToResult < 0 | 
                                 is.na(CollectToResult) | 
                                 is.na(ReceiveToResult), FALSE, TRUE))
  
  sun_master <- raw_sun[ ,c("LocCode", "LocName", "LocandName", 
                            "HISOrderNumber", "PhysName", 
                            "PtNumber", "SHIFT",            
                            "TSTName", "Test", "Division", "SpecimenPriority", 
                            "Site", "ICU", "LocType",               
                            "Setting", "SettingRollUp", 
                            "MasterSetting", "DashboardSetting", 
                            "AdjPriority", "DashboardPriority", 
                            "OrderDateTime", "CollectDateTime", 
                            "ReceiveDateTime", "ResultDateTime", 
                            "ResultedDate", 
                            "CollecttoReceive", "ReceivetoResult", 
                            "CollecttoResult", 
                            "AddOnMaster", "MissingCollect", 
                            "ReceiveResultTarget", "CollectResultTarget", 
                            "ReceiveResultInTarget", "CollectResultInTarget", 
                            "TATInclude")]
  
  colnames(sun_master) <- c("LocCode", "LocName", "LocConcat", 
                            "OrderID", "RequestMD", 
                            "MSMRN", "WorkShift", 
                            "TestName", "Test", "Division", "OrderPriority", 
                            "Site", "ICU", "LocType", 
                            "Setting", "SettingRollUp", 
                            "MasterSetting", "DashboardSetting", 
                            "AdjPriority", "DashboardPriority",
                            "OrderTime", "CollectTime", 
                            "ReceiveTime", "ResultTime", 
                            "ResultDate", 
                            "CollectToReceiveTAT", "ReceiveToResultTAT", 
                            "CollectToResultTAT", 
                            "AddOnMaster", "MissingCollect", 
                            "ReceiveResultTarget", "CollectResultTarget", 
                            "ReceiveResultInTarget", "CollectResultInTarget", 
                            "TATInclude")
  
  
  scc_sun_master <- rbind(scc_master, sun_master)
  
  scc_sun_master[c("LocConcat", "RequestMD", "WorkShift", 
                   "AdjPriority", "AddOnMaster")] <-
    lapply(scc_sun_master[c("LocConcat", "RequestMD", "WorkShift",
                            "AdjPriority", "AddOnMaster")], as.factor)
  
  scc_sun_master$Site <- factor(scc_sun_master$Site, 
                                levels = site_order)
  scc_sun_master$Test <- factor(scc_sun_master$Test, 
                                levels = cp_micro_lab_order)
  scc_sun_master$MasterSetting <- factor(scc_sun_master$MasterSetting, 
                                         levels = pt_setting_order)
  scc_sun_master$DashboardSetting <- factor(scc_sun_master$DashboardSetting, 
                                            levels = pt_setting_order2)
  scc_sun_master$DashboardPriority <- factor(scc_sun_master$DashboardPriority, 
                                             levels = dashboard_priority_order)
  
  scc_sun_list <- list(raw_scc, raw_sun, scc_sun_master)
  
}
```

```{r Analysis without custom function}
raw_scc_test <- scc_wday

# Correct and format any timestamps that were not imported correctly
raw_scc_test[c("ORDERING_DATE", 
            "COLLECTION_DATE", 
            "RECEIVE_DATE", 
            "VERIFIED_DATE")] <-
  lapply(raw_scc_test[c("ORDERING_DATE",
                   "COLLECTION_DATE",
                   "RECEIVE_DATE",
                   "VERIFIED_DATE")],
         function(x)
           ifelse(!is.na(x) & str_detect(x, "\\*.*\\*"),
                  str_replace(x, "\\*.*\\*", ""), x))
                   
raw_scc_test[c("ORDERING_DATE",
          "COLLECTION_DATE",
          "RECEIVE_DATE",
          "VERIFIED_DATE")] <-
  lapply(raw_scc_test[c("ORDERING_DATE",
                   "COLLECTION_DATE",
                   "RECEIVE_DATE",
                   "VERIFIED_DATE")],
         as.POSIXct, tz = "UTC",
         format = "%Y-%m-%d %H:%M:%OS",
         options(digits.sec = 1))

# SCC lookup references ----------------------------------------------
# Crosswalk in scope labs
raw_scc_test <- left_join(raw_scc_test,
                     test_code[ , c("Test", "SCC_TestID", "Division")],
                     by = c("TEST_ID" = "SCC_TestID"))

# Determine if test is included based on crosswalk results
raw_scc_test <- raw_scc_test %>%
  mutate(TestIncl = !is.na(Test)) %>%
  filter(TestIncl)

# Crosswalk unit type
raw_scc_test <- left_join(raw_scc_test, scc_setting,
                     by = c("CLINIC_TYPE" = "Clinic_Type"))
# Crosswalk site name
raw_scc_test <- left_join(raw_scc_test, mshs_site,
                     by = c("SITE" = "DataSite"))

# Crosswalk units and identify ICUs
raw_scc_test <- raw_scc_test %>%
  mutate(WardandName = paste(Ward, WARD_NAME))
  
raw_scc_test <- left_join(raw_scc_test, scc_icu[ , c("Concatenate", "ICU")], 
                       by = c("WardandName" = "Concatenate"))

# Preprocess SCC data and add any necessary columns
raw_scc_test <- raw_scc_test %>%
  mutate(
    # Determine if unit is an ICU based on crosswalk results
    ICU = ifelse(is.na(ICU), FALSE, ICU), 
    # Create a column for resulted date
    ResultedDate = date(VERIFIED_DATE),
    # Create master setting column to identify ICU and IP Non-ICU units
    MasterSetting = ifelse(SettingRollUp == "IP" & ICU, "ICU",
                                 ifelse(SettingRollUp == "IP" & !ICU,
                                        "IP Non-ICU", SettingRollUp)),
    # Create dashboard setting column to roll up master settings based on
    # desired dashboard grouping (ie, group ED and ICU together)
    DashboardSetting = ifelse(MasterSetting %in% c("ED", "ICU"), 
                                    "ED & ICU", MasterSetting),
    # Create column with adjusted priority based on assumption that all ED and
    # ICU labs are treated as stat per operational leadership
    AdjPriority = ifelse(MasterSetting %in% c("ED", "ICU") |
                                   PRIORITY %in% "S", "Stat", "Routine"),
    # Create dashboard priority column 
    DashboardPriority = ifelse(
             tat_targets$Priority[match(Test, tat_targets$Test)] == "All", 
                                      "All", AdjPriority),
    # Calculate turnaround times
    CollectToReceive =
      as.numeric(RECEIVE_DATE - COLLECTION_DATE, units = "mins"),
    ReceiveToResult =
      as.numeric(VERIFIED_DATE - RECEIVE_DATE, units = "mins"),
    CollectToResult =
      as.numeric(VERIFIED_DATE - COLLECTION_DATE, units = "mins"),
    #
    # Determine if order was an add on or original order based on time between
    # order and receive times
    AddOnMaster = ifelse(as.numeric(ORDERING_DATE - RECEIVE_DATE,units = "mins")
                         > 5, "AddOn", "Original"),
    # Determine if collection time is missing
    MissingCollect = CollectToReceive == 0,
    #
    # Determine TAT based on test, priority, and patient setting
    # Create column concatenating test and priority to determine TAT targets
    Concate1 = paste(Test, DashboardPriority),
    # Create column concatenating test, priority, and setting to determine
    # TAT targets
    Concate2 = paste(Test, DashboardPriority, MasterSetting),
    # Determine Receive to Result TAT target using this logic:
    # 1. Try to match test, priority, and setting (applicable for labs with 
    # different TAT targets based on patient setting and order priority)
    # 2. Try to match test and priority (applicable for labs with different
    # TAT targets based on order priority)
    # 3. Try to match test - this is for tests with (applicable for labs with
    # TAT targets that are independent of patient setting or priority)
    #
    # Determine Receive to Result TAT target based on above logic/scenarios
    ReceiveResultTarget =
      # Match on scenario 1
      ifelse(!is.na(match(Concate2, tat_targets$Concate)),
             tat_targets$ReceiveToResultTarget[
               match(Concate2, tat_targets$Concate)],
             # Match on scenario 2
             ifelse(!is.na(match(Concate1, tat_targets$Concate)),
                    tat_targets$ReceiveToResultTarget[
                      match(Concate1, tat_targets$Concate)],
                    # Match on scenario 3
                    tat_targets$ReceiveToResultTarget[
                      match(Test, tat_targets$Concate)])),
    #
    # Determine Collect to Result TAT target based on above logic/scenarios
    CollectResultTarget =
      # Match on scenario 1
      ifelse(!is.na(match(Concate2, tat_targets$Concate)),
             tat_targets$CollectToResultTarget[
               match(Concate2, tat_targets$Concate)],
             # Match on scenario 2
             ifelse(!is.na(match(Concate1, tat_targets$Concate)),
                    tat_targets$CollectToResultTarget[
                      match(Concate1, tat_targets$Concate)],
                    # Match on scenario 3
                    tat_targets$CollectToResultTarget[
                      match(Test, tat_targets$Concate)])),
    #
    # Determine if Receive to Result and Collect to Result TAT meet targets
    ReceiveResultInTarget = ReceiveToResult <= ReceiveResultTarget,
    CollectResultInTarget = CollectToResult <= CollectResultTarget,
    # Create column with patient name, order ID, test, collect, receive, and
    # result date and determine if there is a duplicate; order time excluded
    Concate3 = paste(LAST_NAME, FIRST_NAME,
                     ORDER_ID, TEST_NAME,
                     COLLECTION_DATE, RECEIVE_DATE, VERIFIED_DATE),
    DuplTest = duplicated(Concate3),
    # Determine whether or not to include this particular lab in TAT analysis
    # Exclusion criteria:
    # 1. Add on orders
    # 2. Orders from "Other" settings
    # 3. Orders with collect or receive times after result time
    # 4. Orders with missing collect, receive, or result timestamps
    TATInclude = ifelse(AddOnMaster == "AddOn" |
                          MasterSetting == "Other" |
                          CollectToResult < 0 |
                          ReceiveToResult < 0 |
                          is.na(CollectToResult) |
                          is.na(ReceiveToResult), FALSE, TRUE))

# Remove duplicate tests
raw_scc_test <- raw_scc_test %>%
  filter(!DuplTest)

# Select columns
scc_master_test <- raw_scc_test[ , c("Ward", "WARD_NAME", "WardandName",
                           "ORDER_ID", "REQUESTING_DOC NAME",
                           "MPI", "WORK SHIFT",
                           "TEST_NAME", "Test", "Division", "PRIORITY",
                           "Site", "ICU", "CLINIC_TYPE",
                           "Setting", "SettingRollUp",
                           "MasterSetting", "DashboardSetting",
                           "AdjPriority", "DashboardPriority",
                           "ORDERING_DATE", "COLLECTION_DATE",
                           "RECEIVE_DATE", "VERIFIED_DATE",
                           "ResultedDate",
                           "CollectToReceive", "ReceiveToResult",
                           "CollectToResult",
                           "AddOnMaster", "MissingCollect",
                           "ReceiveResultTarget", "CollectResultTarget",
                           "ReceiveResultInTarget", "CollectResultInTarget",
                           "TATInclude")]
# Rename columns
colnames(scc_master_test) <- c("LocCode", "LocName", "LocConcat",
                          "OrderID", "RequestMD",
                          "MSMRN", "WorkShift",
                          "TestName", "Test", "Division", "OrderPriority",
                          "Site", "ICU", "LocType",
                          "Setting", "SettingRollUp",
                          "MasterSetting", "DashboardSetting",
                          "AdjPriority", "DashboardPriority",
                          "OrderTime", "CollectTime",
                          "ReceiveTime", "ResultTime",
                          "ResultDate",
                          "CollectToReceiveTAT", "ReceiveToResultTAT",
                          "CollectToResultTAT",
                          "AddOnMaster", "MissingCollect",
                          "ReceiveResultTarget", "CollectResultTarget",
                          "ReceiveResultInTarget", "CollectResultInTarget",
                          "TATInclude")

  
## SUNQUEST DATA PROCESSING ----------
# Correct and format any timestamps that were not imported correctly
raw_sun_test <- SQ_Weekday
raw_sun_test[c("OrderDateTime", 
            "CollectDateTime", 
            "ReceiveDateTime", 
            "ResultDateTime")] <- 
    lapply(raw_sun_test[c("OrderDateTime", 
                     "CollectDateTime", 
                     "ReceiveDateTime", 
                     "ResultDateTime")], 
           function(x) ifelse(!is.na(x) & str_detect(x, "\\*.*\\*")  == TRUE, 
                              str_replace(x, "\\*.*\\*", ""), x))

  raw_sun_test[c("OrderDateTime", 
            "CollectDateTime", 
            "ReceiveDateTime", 
            "ResultDateTime")] <- 
    lapply(raw_sun_test[c("OrderDateTime", 
                     "CollectDateTime", 
                     "ReceiveDateTime", 
                     "ResultDateTime")],
           as.POSIXct, tz = "UTC", format = "%m/%d/%Y %H:%M:%S")

# Sunquest lookup references
# Crosswalk labs included and remove out of scope labs
raw_sun_test <- left_join(raw_sun_test, test_code[ , c("Test", 
                                             "SUN_TestCode",
                                             "Division")],
                     by = c("TestCode" = "SUN_TestCode"))

# Determine if test is included based on crosswalk results
raw_sun_test <- raw_sun_test %>%
  mutate(TestIncl = !is.na(Test)) %>%
  filter(TestIncl)

  
# Crosswalk unit type
raw_sun_test <- left_join(raw_sun_test, sun_setting, by = c("LocType" = "LocType"))
  
# Crosswalk site name
raw_sun_test <- left_join(raw_sun_test, mshs_site, by = c("HospCode" = "DataSite"))

# Crosswalk units and identify ICUs
raw_sun_test <- raw_sun_test %>%
  mutate(LocandName = paste(LocCode, LocName))
  
raw_sun_test <- left_join(raw_sun_test, sun_icu[ , c("Concatenate", "ICU")], 
                       by = c("LocandName" = "Concatenate"))

raw_sun_test[is.na(raw_sun_test$ICU), "ICU"] <- FALSE


# # Sunquest data formatting-----------------------------
# Preprocess Sunquest data and add any necessary columns
raw_sun_test <- raw_sun_test %>%
  mutate(
    # Determine if unit is an ICU based on crosswalk results
    ICU = ifelse(is.na(ICU), FALSE, ICU),
    # Create a column for resulted date
    ResultedDate = as.Date(ResultDateTime, format = "%m/%d/%Y"),
    # Create master setting column to identify ICU and IP Non-ICU units
    MasterSetting = ifelse(SettingRollUp == "IP" & ICU, "ICU",
                           ifelse(SettingRollUp == "IP" & !ICU,
                                  "IP Non-ICU", SettingRollUp)),
    # Create dashboard setting column to roll up master settings based on
    # desired dashboard grouping(ie, group ED and ICU together)
    DashboardSetting = ifelse(MasterSetting %in% c("ED", "ICU"), "ED & ICU",
                              MasterSetting),
    #
    # Create column with adjusted priority based on operational assumption that
    # all ED and ICU labs are treated as stat
    AdjPriority = ifelse(MasterSetting %in% c("ED", "ICU") |
                           SpecimenPriority %in% "S", "Stat", "Routine"),
    #
    # Create dashboard priority column
    DashboardPriority = ifelse(
      tat_targets$Priority[match(Test, tat_targets$Test)] == "All", "All",
      AdjPriority),
    #
    # Calculate turnaround times
    CollectToReceive = 
      as.numeric(ReceiveDateTime - CollectDateTime, units = "mins"),
    ReceiveToResult = 
      as.numeric(ResultDateTime - ReceiveDateTime, units = "mins"),
    CollectToResult = 
      as.numeric(ResultDateTime - CollectDateTime, units = "mins"),
    #
    # Determine if order was an add on or original order based on time between
    # order and receive times
    AddOnMaster = ifelse(as.numeric(OrderDateTime - ReceiveDateTime,
                                    units = "mins") > 5, "AddOn", "Original"),
    #
    # Determine if collection time is missing
    MissingCollect = CollectDateTime == OrderDateTime,
    #
    # Determine TAT target based on test, priority, and patient setting
    # Create column concatenating test and priority to determine TAT targets
    Concate1 = paste(Test, DashboardPriority),
    # Create column concatenating test, priority, and setting to determine
    # TAT targets
    Concate2 = paste(Test, DashboardPriority, MasterSetting),
    # Determine Receive to Result TAT target using this logic:
    # 1. Try to match test, priority, and setting (applicable for labs with 
    # different TAT targets based on patient setting and order priority)
    # 2. Try to match test and priority (applicable for labs with different
    # TAT targets based on order priority)
    # 3. Try to match test - this is for tests with (applicable for labs with
    # TAT targets that are independent of patient setting or priority)
    #
    # Determine Receive to Result TAT target based on above logic/scenarios
    ReceiveResultTarget = 
      # Match on scenario 1
      ifelse(!is.na(match(Concate2, tat_targets$Concate)),
             tat_targets$ReceiveToResultTarget[
               match(Concate2, tat_targets$Concate)],
             # Match on scenario 2
             ifelse(!is.na(match(Concate1, tat_targets$Concate)),
                    tat_targets$ReceiveToResultTarget[
                      match(Concate1, tat_targets$Concate)],
                    # Match on scenario 3
                    tat_targets$ReceiveToResultTarget[
                      match(Test, tat_targets$Concate)])),
    #
    # Determine Collect to Result TAT target based on above logic/scenarios
    CollectResultTarget = 
      # Match on scenario 1
      ifelse(!is.na(match(Concate2, tat_targets$Concate)),
             tat_targets$CollectToResultTarget[
               match(Concate2, tat_targets$Concate)],
             # Match on scenario 2
             ifelse(!is.na(match(Concate1, tat_targets$Concate)),
                    tat_targets$CollectToResultTarget[
                      match(Concate1, tat_targets$Concate)],
                    # Match on scenario 3
                    tat_targets$CollectToResultTarget[
                      match(Test, tat_targets$Concate)])),
    #
    # Determine if Receive to Result and Collect to Result TAT meet targets
    ReceiveResultInTarget = ReceiveToResult <= ReceiveResultTarget,
    CollectResultInTarget = CollectToResult <= CollectResultTarget,
    #
    # Create column with patient name, order ID, test, collect, receive, and
    # result date and determine if there is a duplicate; order time excluded
    Concate3 = paste(PtNumber, HISOrderNumber, TSTName, 
                            CollectDateTime, ReceiveDateTime, ResultDateTime),
    DuplTest = duplicated(Concate3),
    #
    # Determine whether or not to include this particular lab in TAT analysis
    # Exclusion criteria:
    # 1. Add on orders
    # 2. Orders from "Other" settings
    # 3. Orders with collect or receive times after result time
    # 4. Orders with missing collect, receive, or result timestamps
    TATInclude = ifelse(AddOnMaster == "AddOn" |
                          MasterSetting == "Other" |
                          CollectToResult < 0 |
                          ReceiveToResult < 0 |
                          is.na(CollectToResult) |
                          is.na(ReceiveToResult), FALSE, TRUE))

# Remove duplicate tests
raw_sun_test <- raw_sun_test %>%
  filter(!DuplTest)

# Select columns
sun_master_test <- raw_sun_test[ ,c("LocCode", "LocName", "LocandName", 
                            "HISOrderNumber", "PhysName", 
                            "PtNumber", "SHIFT",            
                            "TSTName", "Test", "Division", "SpecimenPriority", 
                            "Site", "ICU", "LocType",               
                            "Setting", "SettingRollUp", 
                            "MasterSetting", "DashboardSetting", 
                            "AdjPriority", "DashboardPriority", 
                            "OrderDateTime", "CollectDateTime", 
                            "ReceiveDateTime", "ResultDateTime", 
                            "ResultedDate", 
                            "CollecttoReceive", "ReceivetoResult", 
                            "CollecttoResult", 
                            "AddOnMaster", "MissingCollect", 
                            "ReceiveResultTarget", "CollectResultTarget", 
                            "ReceiveResultInTarget", "CollectResultInTarget", 
                            "TATInclude")]
  
colnames(sun_master_test) <- c("LocCode", "LocName", "LocConcat", 
                            "OrderID", "RequestMD", 
                            "MSMRN", "WorkShift", 
                            "TestName", "Test", "Division", "OrderPriority", 
                            "Site", "ICU", "LocType", 
                            "Setting", "SettingRollUp", 
                            "MasterSetting", "DashboardSetting", 
                            "AdjPriority", "DashboardPriority",
                            "OrderTime", "CollectTime", 
                            "ReceiveTime", "ResultTime", 
                            "ResultDate", 
                            "CollectToReceiveTAT", "ReceiveToResultTAT", 
                            "CollectToResultTAT", 
                            "AddOnMaster", "MissingCollect", 
                            "ReceiveResultTarget", "CollectResultTarget", 
                            "ReceiveResultInTarget", "CollectResultInTarget", 
                            "TATInclude")
  
  
scc_sun_master_test <- rbind(scc_master_test, sun_master_test)

  # scc_sun_master[c("LocConcat", "RequestMD", "WorkShift",
  #                  "AdjPriority", "AddOnMaster")] <-
  #   lapply(scc_sun_master[c("LocConcat", "RequestMD", "WorkShift",
  #                           "AdjPriority", "AddOnMaster")], as.factor)

  scc_sun_master_test$Site <- factor(scc_sun_master_test$Site,
                                levels = site_order)
  scc_sun_master_test$Test <- factor(scc_sun_master_test$Test,
                                levels = cp_micro_lab_order)
  scc_sun_master_test$MasterSetting <- factor(scc_sun_master_test$MasterSetting,
                                         levels = pt_setting_order)
  scc_sun_master_test$DashboardSetting <- factor(scc_sun_master_test$DashboardSetting,
                                            levels = pt_setting_order2)
  scc_sun_master_test$DashboardPriority <- factor(scc_sun_master_test$DashboardPriority,
                                             levels = dashboard_priority_order)

  scc_sun_list <- list(raw_scc_test, raw_sun_test, scc_sun_master_test)
```


```{r scratchpad}
# Create dataframe to compare
scc_master_function <- scc_wday[ , c("Ward", "WARD_NAME", "WardandName",
                           "ORDER_ID", "REQUESTING_DOC NAME",
                           "MPI", "WORK SHIFT",
                           "TEST_NAME", "Test", "Division", "PRIORITY",
                           "Site", "ICU", "CLINIC_TYPE",
                           "Setting", "SettingRollUp",
                           "MasterSetting", "DashboardSetting",
                           "AdjPriority", "DashboardPriority",
                           "ORDERING_DATE", "COLLECTION_DATE",
                           "RECEIVE_DATE", "VERIFIED_DATE",
                           "ResultedDate",
                           "CollectToReceive", "ReceiveToResult",
                           "CollectToResult",
                           "AddOnMaster", "MissingCollect",
                           "ReceiveResultTarget", "CollectResultTarget",
                           "ReceiveResultInTarget", "CollectResultInTarget",
                           "TATInclude")]
# Rename columns
colnames(scc_master_function) <- c("LocCode", "LocName", "LocConcat",
                          "OrderID", "RequestMD",
                          "MSMRN", "WorkShift",
                          "TestName", "Test", "Division", "OrderPriority",
                          "Site", "ICU", "LocType",
                          "Setting", "SettingRollUp",
                          "MasterSetting", "DashboardSetting",
                          "AdjPriority", "DashboardPriority",
                          "OrderTime", "CollectTime",
                          "ReceiveTime", "ResultTime",
                          "ResultDate",
                          "CollectToReceiveTAT", "ReceiveToResultTAT",
                          "CollectToResultTAT",
                          "AddOnMaster", "MissingCollect",
                          "ReceiveResultTarget", "CollectResultTarget",
                          "ReceiveResultInTarget", "CollectResultInTarget",
                          "TATInclude")

scc_master_function <- scc_master_function %>%
  mutate(LocCode = as.character(LocCode),
         LocName = as.character(LocName),
         TestName = as.character(TestName),
         Test = as.character(Test),
         LocType = as.character(LocType),
         Setting = as.character(Setting),
         SettingRollUp = as.character(SettingRollUp),
         Division = as.character(Division),
         Site = as.character(Site))


# Select columns
sun_master_function <- sun_wday[ ,c("LocCode", "LocName", "LocandName", 
                            "HISOrderNumber", "PhysName", 
                            "PtNumber", "SHIFT",            
                            "TSTName", "Test", "Division", "SpecimenPriority", 
                            "Site", "ICU", "LocType",               
                            "Setting", "SettingRollUp", 
                            "MasterSetting", "DashboardSetting", 
                            "AdjPriority", "DashboardPriority", 
                            "OrderDateTime", "CollectDateTime", 
                            "ReceiveDateTime", "ResultDateTime", 
                            "ResultedDate", 
                            "CollecttoReceive", "ReceivetoResult", 
                            "CollecttoResult", 
                            "AddOnMaster", "MissingCollect", 
                            "ReceiveResultTarget", "CollectResultTarget", 
                            "ReceiveResultInTarget", "CollectResultInTarget", 
                            "TATInclude")]
  
colnames(sun_master_function) <- c("LocCode", "LocName", "LocConcat", 
                            "OrderID", "RequestMD", 
                            "MSMRN", "WorkShift", 
                            "TestName", "Test", "Division", "OrderPriority", 
                            "Site", "ICU", "LocType", 
                            "Setting", "SettingRollUp", 
                            "MasterSetting", "DashboardSetting", 
                            "AdjPriority", "DashboardPriority",
                            "OrderTime", "CollectTime", 
                            "ReceiveTime", "ResultTime", 
                            "ResultDate", 
                            "CollectToReceiveTAT", "ReceiveToResultTAT", 
                            "CollectToResultTAT", 
                            "AddOnMaster", "MissingCollect", 
                            "ReceiveResultTarget", "CollectResultTarget", 
                            "ReceiveResultInTarget", "CollectResultInTarget", 
                            "TATInclude")

sun_master_function <- sun_master_function %>%
  mutate(LocCode = as.character(LocCode),
         LocName = as.character(LocName),
         LocConcat = as.character(LocConcat),
         RequestMD = as.character(RequestMD),
         WorkShift = as.character(WorkShift),
         TestName = as.character(TestName),
         Test = as.character(Test),
         Division = as.character(Division),
         Site = as.character(Site),
         LocType = as.character(LocType),
         Setting = as.character(Setting),
         SettingRollUp = as.character(SettingRollUp))


```

```{r New concise function for preprocessing SCC and Sunquest data}
preprocess_scc_sun_newfunc <- function(raw_scc, raw_sun)  {
  
  # Preprocess SCC data -------------------------------
  # Correct and format any timestamps that were not imported correctly
  raw_scc[c("ORDERING_DATE", 
            "COLLECTION_DATE", 
            "RECEIVE_DATE", 
            "VERIFIED_DATE")] <-
    lapply(raw_scc[c("ORDERING_DATE",
                     "COLLECTION_DATE",
                     "RECEIVE_DATE",
                     "VERIFIED_DATE")],
           function(x)
             ifelse(!is.na(x) & str_detect(x, "\\*.*\\*"),
                    str_replace(x, "\\*.*\\*", ""), x))
  
  raw_scc[c("ORDERING_DATE",
            "COLLECTION_DATE",
            "RECEIVE_DATE",
            "VERIFIED_DATE")] <-
    lapply(raw_scc[c("ORDERING_DATE",
                     "COLLECTION_DATE",
                     "RECEIVE_DATE",
                     "VERIFIED_DATE")],
           as.POSIXct, tz = "UTC",
           format = "%Y-%m-%d %H:%M:%OS",
           options(digits.sec = 1))
  
  # SCC lookup references ----------------------------------------------
  # Crosswalk in scope labs
  raw_scc <- left_join(raw_scc,
                       test_code[ , c("Test", "SCC_TestID", "Division")],
                       by = c("TEST_ID" = "SCC_TestID"))
  
  # Determine if test is included based on crosswalk results
  raw_scc <- raw_scc %>%
    mutate(TestIncl = !is.na(Test)) %>%
    filter(TestIncl)
  
  # Crosswalk unit type
  raw_scc <- left_join(raw_scc, scc_setting,
                       by = c("CLINIC_TYPE" = "Clinic_Type"))
  # Crosswalk site name
  raw_scc <- left_join(raw_scc, mshs_site,
                       by = c("SITE" = "DataSite"))
  
  # Crosswalk units and identify ICUs
  raw_scc <- raw_scc %>%
    mutate(WardandName = paste(Ward, WARD_NAME))
  
  raw_scc <- left_join(raw_scc, scc_icu[ , c("Concatenate", "ICU")], 
                       by = c("WardandName" = "Concatenate"))
  
  # Preprocess SCC data and add any necessary columns
  raw_scc <- raw_scc %>%
    mutate(
      # Determine if unit is an ICU based on crosswalk results
      ICU = ifelse(is.na(ICU), FALSE, ICU), 
      # Create a column for resulted date
      ResultedDate = date(VERIFIED_DATE),
      # Create master setting column to identify ICU and IP Non-ICU units
      MasterSetting = ifelse(SettingRollUp == "IP" & ICU, "ICU",
                             ifelse(SettingRollUp == "IP" & !ICU,
                                    "IP Non-ICU", SettingRollUp)),
      # Create dashboard setting column to roll up master settings based on
      # desired dashboard grouping (ie, group ED and ICU together)
      DashboardSetting = ifelse(MasterSetting %in% c("ED", "ICU"), 
                                "ED & ICU", MasterSetting),
      # Create column with adjusted priority based on assumption that all ED and
      # ICU labs are treated as stat per operational leadership
      AdjPriority = ifelse(MasterSetting %in% c("ED", "ICU") |
                             PRIORITY %in% "S", "Stat", "Routine"),
      # Create dashboard priority column 
      DashboardPriority = ifelse(
        tat_targets$Priority[match(Test, tat_targets$Test)] == "All", 
        "All", AdjPriority),
      # Calculate turnaround times
      CollectToReceive =
        as.numeric(RECEIVE_DATE - COLLECTION_DATE, units = "mins"),
      ReceiveToResult =
        as.numeric(VERIFIED_DATE - RECEIVE_DATE, units = "mins"),
      CollectToResult =
        as.numeric(VERIFIED_DATE - COLLECTION_DATE, units = "mins"),
      #
      # Determine if order was an add on or original order based on time between
      # order and receive times
      AddOnMaster = ifelse(as.numeric(ORDERING_DATE - RECEIVE_DATE,units = "mins")
                           > 5, "AddOn", "Original"),
      # Determine if collection time is missing
      MissingCollect = CollectToReceive == 0,
      #
      # Determine TAT based on test, priority, and patient setting
      # Create column concatenating test and priority to determine TAT targets
      Concate1 = paste(Test, DashboardPriority),
      # Create column concatenating test, priority, and setting to determine
      # TAT targets
      Concate2 = paste(Test, DashboardPriority, MasterSetting),
      # Determine Receive to Result TAT target using this logic:
      # 1. Try to match test, priority, and setting (applicable for labs with 
      # different TAT targets based on patient setting and order priority)
      # 2. Try to match test and priority (applicable for labs with different
      # TAT targets based on order priority)
      # 3. Try to match test - this is for tests with (applicable for labs with
      # TAT targets that are independent of patient setting or priority)
      #
      # Determine Receive to Result TAT target based on above logic/scenarios
      ReceiveResultTarget =
        # Match on scenario 1
        ifelse(!is.na(match(Concate2, tat_targets$Concate)),
               tat_targets$ReceiveToResultTarget[
                 match(Concate2, tat_targets$Concate)],
               # Match on scenario 2
               ifelse(!is.na(match(Concate1, tat_targets$Concate)),
                      tat_targets$ReceiveToResultTarget[
                        match(Concate1, tat_targets$Concate)],
                      # Match on scenario 3
                      tat_targets$ReceiveToResultTarget[
                        match(Test, tat_targets$Concate)])),
      #
      # Determine Collect to Result TAT target based on above logic/scenarios
      CollectResultTarget =
        # Match on scenario 1
        ifelse(!is.na(match(Concate2, tat_targets$Concate)),
               tat_targets$CollectToResultTarget[
                 match(Concate2, tat_targets$Concate)],
               # Match on scenario 2
               ifelse(!is.na(match(Concate1, tat_targets$Concate)),
                      tat_targets$CollectToResultTarget[
                        match(Concate1, tat_targets$Concate)],
                      # Match on scenario 3
                      tat_targets$CollectToResultTarget[
                        match(Test, tat_targets$Concate)])),
      #
      # Determine if Receive to Result and Collect to Result TAT meet targets
      ReceiveResultInTarget = ReceiveToResult <= ReceiveResultTarget,
      CollectResultInTarget = CollectToResult <= CollectResultTarget,
      # Create column with patient name, order ID, test, collect, receive, and
      # result date and determine if there is a duplicate; order time excluded
      Concate3 = paste(LAST_NAME, FIRST_NAME,
                       ORDER_ID, TEST_NAME,
                       COLLECTION_DATE, RECEIVE_DATE, VERIFIED_DATE),
      DuplTest = duplicated(Concate3),
      # Determine whether or not to include this particular lab in TAT analysis
      # Exclusion criteria:
      # 1. Add on orders
      # 2. Orders from "Other" settings
      # 3. Orders with collect or receive times after result time
      # 4. Orders with missing collect, receive, or result timestamps
      TATInclude = ifelse(AddOnMaster == "AddOn" |
                            MasterSetting == "Other" |
                            CollectToResult < 0 |
                            ReceiveToResult < 0 |
                            is.na(CollectToResult) |
                            is.na(ReceiveToResult), FALSE, TRUE))
  
  # Remove duplicate tests
  raw_scc <- raw_scc %>%
    filter(!DuplTest)
  
  # Select columns
  scc_master_newfunc <- raw_scc[ , c("Ward", "WARD_NAME", "WardandName",
                              "ORDER_ID", "REQUESTING_DOC NAME",
                              "MPI", "WORK SHIFT",
                              "TEST_NAME", "Test", "Division", "PRIORITY",
                              "Site", "ICU", "CLINIC_TYPE",
                              "Setting", "SettingRollUp",
                              "MasterSetting", "DashboardSetting",
                              "AdjPriority", "DashboardPriority",
                              "ORDERING_DATE", "COLLECTION_DATE",
                              "RECEIVE_DATE", "VERIFIED_DATE",
                              "ResultedDate",
                              "CollectToReceive", "ReceiveToResult",
                              "CollectToResult",
                              "AddOnMaster", "MissingCollect",
                              "ReceiveResultTarget", "CollectResultTarget",
                              "ReceiveResultInTarget", "CollectResultInTarget",
                              "TATInclude")]
  # Rename columns
  colnames(scc_master_newfunc) <- c("LocCode", "LocName", "LocConcat",
                             "OrderID", "RequestMD",
                             "MSMRN", "WorkShift",
                             "TestName", "Test", "Division", "OrderPriority",
                             "Site", "ICU", "LocType",
                             "Setting", "SettingRollUp",
                             "MasterSetting", "DashboardSetting",
                             "AdjPriority", "DashboardPriority",
                             "OrderTime", "CollectTime",
                             "ReceiveTime", "ResultTime",
                             "ResultDate",
                             "CollectToReceiveTAT", "ReceiveToResultTAT",
                             "CollectToResultTAT",
                             "AddOnMaster", "MissingCollect",
                             "ReceiveResultTarget", "CollectResultTarget",
                             "ReceiveResultInTarget", "CollectResultInTarget",
                             "TATInclude")
  
  # Preprocess Sunquest data --------------------------------
  # Correct and format any timestamps that were not imported correctly
  # raw_sun <- SQ_Weekday
  raw_sun[c("OrderDateTime", 
            "CollectDateTime", 
            "ReceiveDateTime", 
            "ResultDateTime")] <- 
    lapply(raw_sun[c("OrderDateTime", 
                     "CollectDateTime", 
                     "ReceiveDateTime", 
                     "ResultDateTime")], 
           function(x) ifelse(!is.na(x) & str_detect(x, "\\*.*\\*")  == TRUE, 
                              str_replace(x, "\\*.*\\*", ""), x))
  
  raw_sun[c("OrderDateTime", 
            "CollectDateTime", 
            "ReceiveDateTime", 
            "ResultDateTime")] <- 
    lapply(raw_sun[c("OrderDateTime", 
                     "CollectDateTime", 
                     "ReceiveDateTime", 
                     "ResultDateTime")],
           as.POSIXct, tz = "UTC", format = "%m/%d/%Y %H:%M:%S")
  
  # Sunquest lookup references
  # Crosswalk labs included and remove out of scope labs
  raw_sun <- left_join(raw_sun, test_code[ , c("Test", 
                                               "SUN_TestCode",
                                               "Division")],
                       by = c("TestCode" = "SUN_TestCode"))
  
  # Determine if test is included based on crosswalk results
  raw_sun <- raw_sun %>%
    mutate(TestIncl = !is.na(Test)) %>%
    filter(TestIncl)
  
  
  # Crosswalk unit type
  raw_sun <- left_join(raw_sun, sun_setting, by = c("LocType" = "LocType"))
  
  # Crosswalk site name
  raw_sun <- left_join(raw_sun, mshs_site, by = c("HospCode" = "DataSite"))
  
  # Crosswalk units and identify ICUs
  raw_sun <- raw_sun %>%
    mutate(LocandName = paste(LocCode, LocName))
  
  raw_sun <- left_join(raw_sun, sun_icu[ , c("Concatenate", "ICU")], 
                       by = c("LocandName" = "Concatenate"))
  
  raw_sun[is.na(raw_sun$ICU), "ICU"] <- FALSE
  
  
  # # Sunquest data formatting-----------------------------
  # Preprocess Sunquest data and add any necessary columns
  raw_sun <- raw_sun %>%
    mutate(
      # Determine if unit is an ICU based on crosswalk results
      ICU = ifelse(is.na(ICU), FALSE, ICU),
      # Create a column for resulted date
      ResultedDate = as.Date(ResultDateTime, format = "%m/%d/%Y"),
      # Create master setting column to identify ICU and IP Non-ICU units
      MasterSetting = ifelse(SettingRollUp == "IP" & ICU, "ICU",
                             ifelse(SettingRollUp == "IP" & !ICU,
                                    "IP Non-ICU", SettingRollUp)),
      # Create dashboard setting column to roll up master settings based on
      # desired dashboard grouping(ie, group ED and ICU together)
      DashboardSetting = ifelse(MasterSetting %in% c("ED", "ICU"), "ED & ICU",
                                MasterSetting),
      #
      # Create column with adjusted priority based on operational assumption that
      # all ED and ICU labs are treated as stat
      AdjPriority = ifelse(MasterSetting %in% c("ED", "ICU") |
                             SpecimenPriority %in% "S", "Stat", "Routine"),
      #
      # Create dashboard priority column
      DashboardPriority = ifelse(
        tat_targets$Priority[match(Test, tat_targets$Test)] == "All", "All",
        AdjPriority),
      #
      # Calculate turnaround times
      CollectToReceive = 
        as.numeric(ReceiveDateTime - CollectDateTime, units = "mins"),
      ReceiveToResult = 
        as.numeric(ResultDateTime - ReceiveDateTime, units = "mins"),
      CollectToResult = 
        as.numeric(ResultDateTime - CollectDateTime, units = "mins"),
      #
      # Determine if order was an add on or original order based on time between
      # order and receive times
      AddOnMaster = ifelse(as.numeric(OrderDateTime - ReceiveDateTime,
                                      units = "mins") > 5, "AddOn", "Original"),
      #
      # Determine if collection time is missing
      MissingCollect = CollectDateTime == OrderDateTime,
      #
      # Determine TAT target based on test, priority, and patient setting
      # Create column concatenating test and priority to determine TAT targets
      Concate1 = paste(Test, DashboardPriority),
      # Create column concatenating test, priority, and setting to determine
      # TAT targets
      Concate2 = paste(Test, DashboardPriority, MasterSetting),
      # Determine Receive to Result TAT target using this logic:
      # 1. Try to match test, priority, and setting (applicable for labs with 
      # different TAT targets based on patient setting and order priority)
      # 2. Try to match test and priority (applicable for labs with different
      # TAT targets based on order priority)
      # 3. Try to match test - this is for tests with (applicable for labs with
      # TAT targets that are independent of patient setting or priority)
      #
      # Determine Receive to Result TAT target based on above logic/scenarios
      ReceiveResultTarget = 
        # Match on scenario 1
        ifelse(!is.na(match(Concate2, tat_targets$Concate)),
               tat_targets$ReceiveToResultTarget[
                 match(Concate2, tat_targets$Concate)],
               # Match on scenario 2
               ifelse(!is.na(match(Concate1, tat_targets$Concate)),
                      tat_targets$ReceiveToResultTarget[
                        match(Concate1, tat_targets$Concate)],
                      # Match on scenario 3
                      tat_targets$ReceiveToResultTarget[
                        match(Test, tat_targets$Concate)])),
      #
      # Determine Collect to Result TAT target based on above logic/scenarios
      CollectResultTarget = 
        # Match on scenario 1
        ifelse(!is.na(match(Concate2, tat_targets$Concate)),
               tat_targets$CollectToResultTarget[
                 match(Concate2, tat_targets$Concate)],
               # Match on scenario 2
               ifelse(!is.na(match(Concate1, tat_targets$Concate)),
                      tat_targets$CollectToResultTarget[
                        match(Concate1, tat_targets$Concate)],
                      # Match on scenario 3
                      tat_targets$CollectToResultTarget[
                        match(Test, tat_targets$Concate)])),
      #
      # Determine if Receive to Result and Collect to Result TAT meet targets
      ReceiveResultInTarget = ReceiveToResult <= ReceiveResultTarget,
      CollectResultInTarget = CollectToResult <= CollectResultTarget,
      #
      # Create column with patient name, order ID, test, collect, receive, and
      # result date and determine if there is a duplicate; order time excluded
      Concate3 = paste(PtNumber, HISOrderNumber, TSTName, 
                       CollectDateTime, ReceiveDateTime, ResultDateTime),
      DuplTest = duplicated(Concate3),
      #
      # Determine whether or not to include this particular lab in TAT analysis
      # Exclusion criteria:
      # 1. Add on orders
      # 2. Orders from "Other" settings
      # 3. Orders with collect or receive times after result time
      # 4. Orders with missing collect, receive, or result timestamps
      TATInclude = ifelse(AddOnMaster == "AddOn" |
                            MasterSetting == "Other" |
                            CollectToResult < 0 |
                            ReceiveToResult < 0 |
                            is.na(CollectToResult) |
                            is.na(ReceiveToResult), FALSE, TRUE))
  
  # Remove duplicate tests
  raw_sun <- raw_sun %>%
    filter(!DuplTest)
  
  # Select columns
  sun_master_newfunc <- raw_sun[ ,c("LocCode", "LocName", "LocandName", 
                             "HISOrderNumber", "PhysName", 
                             "PtNumber", "SHIFT",            
                             "TSTName", "Test", "Division", "SpecimenPriority", 
                             "Site", "ICU", "LocType",               
                             "Setting", "SettingRollUp", 
                             "MasterSetting", "DashboardSetting", 
                             "AdjPriority", "DashboardPriority", 
                             "OrderDateTime", "CollectDateTime", 
                             "ReceiveDateTime", "ResultDateTime", 
                             "ResultedDate", 
                             "CollecttoReceive", "ReceivetoResult", 
                             "CollecttoResult", 
                             "AddOnMaster", "MissingCollect", 
                             "ReceiveResultTarget", "CollectResultTarget", 
                             "ReceiveResultInTarget", "CollectResultInTarget", 
                             "TATInclude")]
  
  colnames(sun_master_newfunc) <- c("LocCode", "LocName", "LocConcat", 
                             "OrderID", "RequestMD", 
                             "MSMRN", "WorkShift", 
                             "TestName", "Test", "Division", "OrderPriority", 
                             "Site", "ICU", "LocType", 
                             "Setting", "SettingRollUp", 
                             "MasterSetting", "DashboardSetting", 
                             "AdjPriority", "DashboardPriority",
                             "OrderTime", "CollectTime", 
                             "ReceiveTime", "ResultTime", 
                             "ResultDate", 
                             "CollectToReceiveTAT", "ReceiveToResultTAT", 
                             "CollectToResultTAT", 
                             "AddOnMaster", "MissingCollect", 
                             "ReceiveResultTarget", "CollectResultTarget", 
                             "ReceiveResultInTarget", "CollectResultInTarget", 
                             "TATInclude")

  
  scc_sun_master <- rbind(scc_master_newfunc, sun_master_newfunc)
  
  # scc_sun_master[c("LocConcat", "RequestMD", "WorkShift", 
  #                  "AdjPriority", "AddOnMaster")] <-
  #   lapply(scc_sun_master[c("LocConcat", "RequestMD", "WorkShift",
  #                           "AdjPriority", "AddOnMaster")], as.factor)
  
  scc_sun_master$Site <- factor(scc_sun_master$Site, 
                                levels = site_order)
  scc_sun_master$Test <- factor(scc_sun_master$Test, 
                                levels = cp_micro_lab_order)
  scc_sun_master$MasterSetting <- factor(scc_sun_master$MasterSetting, 
                                         levels = pt_setting_order)
  scc_sun_master$DashboardSetting <- factor(scc_sun_master$DashboardSetting, 
                                            levels = pt_setting_order2)
  scc_sun_master$DashboardPriority <- factor(scc_sun_master$DashboardPriority, 
                                             levels = dashboard_priority_order)
  
  scc_sun_list_newfunc <- list(raw_scc, raw_sun, 
                       scc_master_newfunc, sun_master_newfunc,
                       scc_sun_master)
  
}
```

```{r}
# Preprocess data
scc_sun_wday_list <-preprocess_scc_sun_newfunc(raw_scc = SCC_Weekday, raw_sun = SQ_Weekday)

scc_wday <- scc_sun_wday_list[[1]]
sun_wday <- scc_sun_wday_list[[2]]
scc_sun_wday_master <- scc_sun_wday_list[[5]]

if (is.null(SQ_Not_Weekday) & is.null(SCC_Not_Weekday)) {
  include_not_wday <- FALSE
  scc_sun_not_wday_list <- NULL
  scc_not_wday <- NULL
  sun_not_wday <- NULL
  scc_sun_not_wday_master <- NULL
} else {
  include_not_wday <- TRUE
  scc_sun_not_wday_list <- preprocess_scc_sun_newfunc(
    raw_scc = SCC_Not_Weekday,
    raw_sun = SQ_Not_Weekday)
  scc_not_wday <- scc_sun_not_wday_list[[1]]
  sun_not_wday <- scc_sun_not_wday_list[[2]]
  scc_sun_not_wday_master <- scc_sun_not_wday_list[[5]]
}

# Remove labs from master data frame that were resulted at exactly midnight on 
# next morning or prior day
# Custom function to determine correct number of dates
correct_scc_result_dates <- function(data, number_days) {
  all_resulted_dates_vol <- data %>%
    group_by(ResultDate) %>%
    summarize(VolLabs = n()) %>%
    arrange(desc(VolLabs)) %>%
    ungroup()
  
  correct_dates <- all_resulted_dates_vol$ResultDate[1:number_days]
  
  new_data <- data %>%
    filter(ResultDate %in% correct_dates)
  
  return(new_data)
}

# Update preprocessed data to only include correct dates ----------------------
scc_sun_wday_master <- correct_scc_result_dates(scc_sun_wday_master, 1)

if (scenario == 1) {
  scc_sun_not_wday_master <- correct_scc_result_dates(scc_sun_not_wday_master, 
                                                      3)
} else if (scenario == 2) {
  scc_sun_not_wday_master <- correct_scc_result_dates(scc_sun_not_wday_master, 
                                                      2)
} else if (scenario == 3) {
  scc_sun_not_wday_master <- correct_scc_result_dates(scc_sun_not_wday_master, 
                                                      1)
}

# Determine resulted date for weekday labs
wday_result_date <- format(unique(scc_sun_wday_master$ResultDate), 
                           format = "%a %m/%d/%y")

```

```{r Template dataframe}
# Create a template data frame for combinations of tests, priority and settings
test_name_division <- unique(test_code[, c("Division", "Test")])

test_names <- unique(test_code$Test)

# Create data frame of test and site combinations
rep_test_site <- sort(rep(test_names, length(city_sites)))

rep_sites <- rep(city_sites, length(test_names))

test_site_comb <- data.frame("Test" = rep_test_site,
                             "Site" = rep_sites,
                             stringsAsFactors = FALSE)

# Create data frame of test and priority combinations
rep_test_priority <- sort(rep(test_names, length(dashboard_priority_order)))

rep_priority <- rep(dashboard_priority_order, length(test_names))

test_priority_comb <- data.frame("Test" = rep_test_priority,
                                "DashboardPriority" = rep_priority,
                                stringsAsFactors = FALSE)

# Create data frame of test and setting combinations
rep_test_setting <- sort(rep(test_names, length(dashboard_pt_setting)))

rep_setting <- rep(dashboard_pt_setting, length(test_names))

test_setting_comb <- data.frame("Test" = rep_test_setting,
                                "DashboardSetting" = rep_setting)

# Combine data frames to create data frame with all combinations of tests,
# sites, priority, and settings
test_site_prty <- left_join(test_site_comb,
                            test_priority_comb,
                            by = c("Test" = "Test"))

test_site_prty_setting <- left_join(test_site_prty,
                                   test_setting_comb,
                                   by = c("Test" = "Test"))

test_site_prty_setting <- left_join(test_site_prty_setting,
                                    unique(test_code[, c("Test", "Division")]),
                                    by = c("Test" = "Test"))

# Select applicable test, priority, setting combinations based on lab operations
test_site_prty_setting_templ <- test_site_prty_setting %>%
  mutate(
    # Create column for applicable combinations
    Incl = ifelse(
      # Remove ED & ICU labs with Routine priority since all labs in these
      # these settings are treated as stat
      (DashboardPriority %in% c("Routine") &
         DashboardSetting %in% c("ED & ICU")) |
        # Remove ambulatory troponin and lactate since these labs are collected
        # in ambulatory settings. Remove stat and routine stratification for
        # these labs since all are treated as stat.
        (Test %in% c("Troponin", "Lactate WB") &
           (DashboardPriority %in% c("Stat", "Routine") |
              DashboardSetting %in% c("Amb"))) |
        # Remove "all" priority for BUN, PT, and HGB labs
        (Test %in% c("BUN", "PT", "HGB") & DashboardPriority %in% c("All")) |
        # Remove priority stratification for rapid flu and c. diff since all are treated
        # as stat
        (Test %in% c("Rapid Flu", "C. diff") & !(DashboardPriority %in% c("All"))),
      "Excl", "Incl")) %>%
  filter(Incl == "Incl")

```

```{r Function to summarize data for each lab division}
# Custom function to subset, summarize, clean, and format data for dashboards for all lab divisions
lab_sub_summarize <- function(x, LabDivision) {
  #
  # Subset data to be included based on lab division and whether or not TAT
  # meets inclusion criteria
  lab_df <- x[x$Division == LabDivision & x$TATInclude == TRUE, ]
  #
  # Update factors
  lab_df$Test <- factor(lab_df$Test,
                        unique(test_code$Test[
                          test_code$Division == LabDivision]))
  lab_df$DashboardSetting <- factor(lab_df$DashboardSetting,
                                    dashboard_pt_setting)
  lab_df$DashboardPriority <- droplevels(lab_df$DashboardPriority)
  #
  # Summarize data based on test, site, priority, setting, and TAT targets.
  # Keep levels so each site is maintained for melting/casting later.
  lab_summary <- lab_df %>%
    group_by(Test,
             Site,
             DashboardPriority,
             DashboardSetting,
             ReceiveResultTarget,
             CollectResultTarget,
             .drop = FALSE) %>%
  summarize(ResultedVolume = n(),
            ReceiveResultInTarget = sum(ReceiveResultInTarget),
            CollectResultInTarget = sum(CollectResultInTarget),
            ReceiveResultPercent = round(ReceiveResultInTarget/ResultedVolume,
                                         digits = 3),
            CollectResultPercent = round(CollectResultInTarget/ResultedVolume,
                                         digits = 3))
  #
  # Clean up summarized data
  # Replace NaN TAT percentages with NA
  lab_summary[!is.finite(lab_summary$ReceiveResultPercent),
              "ReceiveResultPercent"] <- NA
  lab_summary[!is.finite(lab_summary$CollectResultPercent),
              "CollectResultPercent"] <- NA
  #
  # Look up target TAT for sites with 0 resulted labs using tat_targets reference
  lab_summary$Concate1 <- paste(lab_summary$Test,
                                lab_summary$DashboardPriority)
  lab_summary$Concate2 <- paste(lab_summary$Test,
                                lab_summary$DashboardPriority,
                                lab_summary$DashboardSetting)
  #
  lab_summary$ReceiveResultTarget[is.na(lab_summary$ReceiveResultTarget)] <-
    ifelse(!is.na(match(lab_summary$Concate2[
      is.na(lab_summary$ReceiveResultTarget)], tat_targets$Concate)),
      tat_targets$ReceiveToResultTarget[
        match(lab_summary$Concate2[is.na(lab_summary$ReceiveResultTarget)],
              tat_targets$Concate)],
      ifelse(!is.na(match(lab_summary$Concate1[
        is.na(lab_summary$ReceiveResultTarget)], tat_targets$Concate)),
        tat_targets$ReceiveToResultTarget[
          match(lab_summary$Concate1[is.na(lab_summary$ReceiveResultTarget)],
                tat_targets$Concate)],
        tat_targets$ReceiveToResultTarget[match(lab_summary$Test[
          is.na(lab_summary$ReceiveResultTarget)], tat_targets$Concate)]))
  #
  lab_summary$CollectResultTarget[is.na(lab_summary$CollectResultTarget)] <-
    ifelse(!is.na(match(lab_summary$Concate2[
      is.na(lab_summary$CollectResultTarget)], tat_targets$Concate)),
      tat_targets$CollectToResultTarget[
        match(lab_summary$Concate2[is.na(lab_summary$CollectResultTarget)],
              tat_targets$Concate)],
      ifelse(!is.na(match(lab_summary$Concate1[
        is.na(lab_summary$CollectResultTarget)], tat_targets$Concate)),
        tat_targets$CollectToResultTarget[
          match(lab_summary$Concate1[is.na(lab_summary$CollectResultTarget)],
                tat_targets$Concate)],
        tat_targets$CollectToResultTarget[
          match(lab_summary$Test[is.na(lab_summary$CollectResultTarget)],
                tat_targets$Concate)]))
  # Remove concatenated columns
  lab_summary$Concate1 <- NULL
  lab_summary$Concate2 <- NULL
  #
  # Format target TAT for tables from numbers to "<=X min"
  lab_summary[c("ReceiveResultTarget", "CollectResultTarget")] <-
    lapply(lab_summary[c("ReceiveResultTarget", "CollectResultTarget")],
           function(y) ifelse(is.na(y), y, paste0("<=", y, " min")))
  #
  lab_summary[c("ReceiveResultPercent", "CollectResultPercent")] <-
    lapply(lab_summary[c("ReceiveResultPercent", "CollectResultPercent")],
           percent, digits = 0)
  #
  # Create new column with test and priority to be used in tables later
  lab_summary$TestAndPriority <- paste(lab_summary$Test, "-",
                                       lab_summary$DashboardPriority, "Labs")
  #
  # Remove unused combinations, specifically Routine ED & ICU labs
  lab_summary <- lab_summary[!(lab_summary$DashboardPriority == "Routine" &
                                 lab_summary$DashboardSetting == "ED & ICU"), ]
  #
  # Apply conditional color formatting to TAT percentages based on status definitions for each lab division
  lab_summary <- lab_summary %>%
    mutate(ReceiveResultPercent = cell_spec(
      ReceiveResultPercent, "html",
      color = ifelse(is.na(ReceiveResultPercent), "lightgray",
                     ifelse(((ReceiveResultPercent >= 0.95 &
                                (LabDivision == "Chemistry" |
                                   LabDivision == "Hematology")) |
                               (ReceiveResultPercent == 1.00 &
                                  LabDivision == "Microbiology RRL")), "green",
                            ifelse(((ReceiveResultPercent >=0.8 &
                                       ReceiveResultPercent < 0.95 &
                                       (LabDivision == "Chemistry" |
                                          LabDivision == "Hematology")) |
                                      (ReceiveResultPercent >= 0.90 &
                                         ReceiveResultPercent < 1.0 &
                                         LabDivision == "Microbiology RRL")),
                                   "orange", "red")))))
  #
  lab_summary <- lab_summary %>%
    mutate(CollectResultPercent = cell_spec(
      CollectResultPercent, "html",
      color = ifelse(is.na(CollectResultPercent), "lightgray",
                     ifelse(((CollectResultPercent >= 0.95 &
                                (LabDivision == "Chemistry" |
                                   LabDivision == "Hematology")) |
                               (CollectResultPercent == 1.00 &
                                  LabDivision == "Microbiology RRL")), "green",
                            ifelse(((CollectResultPercent >=0.8 &
                                       CollectResultPercent < 0.95 &
                                       (LabDivision == "Chemistry" |
                                          LabDivision == "Hematology")) |
                                      (CollectResultPercent >= 0.90 &
                                         CollectResultPercent < 1.0 &
                                         LabDivision == "Microbiology RRL")),
                                   "orange", "red")))))
  #
  # Melt summarized data into a long dataframe
  lab_dashboard1 <- melt(lab_summary,
                         id.var = c("Test",
                                    "Site",
                                    "DashboardPriority",
                                    "TestAndPriority",
                                    "DashboardSetting",
                                    "ReceiveResultTarget",
                                    "CollectResultTarget"),
                         measure.vars = c("ReceiveResultPercent",
                                          "CollectResultPercent"))
  # Cast dataframe into wide format for use in tables later
  lab_dashboard2 <- dcast(lab_dashboard1,
                          Test +
                            DashboardPriority +
                            TestAndPriority +
                            DashboardSetting +
                            ReceiveResultTarget +
                            CollectResultTarget ~
                            variable +
                            Site,
                          value.var = "value")
  # Rearrange casted dataframe columns based on desired table aesthetics
  lab_dashboard2 <- lab_dashboard2[ , c(1:3, 5, 4, 7:12, 6, 4, 13:18)]
  # Save outputs in a list
  lab_sub_output <- list(lab_df, lab_summary, lab_dashboard1, lab_dashboard2)
  lab_sub_output
}


```

```{r Analysis for lab division summaries}
#
# Subset data to be included based on lab division and whether or not TAT
# meets inclusion criteria
lab_test_df <- scc_sun_wday_master %>%
  filter(Division == "Chemistry" & TATInclude & Site %in% city_sites)


# lab_df <- x[x$Division == LabDivision & x$TATInclude == TRUE, ]
#
# Update factors
# lab_df$Test <- factor(lab_df$Test,
#                         unique(test_code$Test[
#                           test_code$Division == LabDivision]))
#   lab_df$DashboardSetting <- factor(lab_df$DashboardSetting,
#                                     dashboard_pt_setting)
#   lab_df$DashboardPriority <- droplevels(lab_df$DashboardPriority)
#
# Summarize data based on test, site, priority, setting, and TAT targets.
# Keep levels so each site is maintained for melting/casting later.
lab_summary <- lab_test_df %>%
  group_by(Test,
           Site,
           DashboardPriority,
           DashboardSetting,
           ReceiveResultTarget,
           CollectResultTarget) %>%
  summarize(ResultedVolume = n(),
            ReceiveResultInTarget = sum(ReceiveResultInTarget),
            CollectResultInTarget = sum(CollectResultInTarget),
            ReceiveResultPercent = round(ReceiveResultInTarget/ResultedVolume,
                                         digits = 3),
            CollectResultPercent = round(CollectResultInTarget/ResultedVolume,
                                         digits = 3),
            .groups = "keep") %>%
  ungroup()

# Combine lab summary with template data frame for this lab division
chem_df_templ <- test_site_prty_setting_templ %>%
  mutate(Incl = NULL) %>%
  filter(Division == "Chemistry")

lab_summary <- left_join(chem_df_templ, lab_summary,
                         by = c("Test" = "Test",
                                "Site" = "Site",
                                "DashboardPriority" = "DashboardPriority",
                                "DashboardSetting" = "DashboardSetting"))

#
# Look up target TAT for sites with 0 resulted labs using tat_targets reference
lab_summary_test <- lab_summary %>%
  mutate(
    #
    # Set test, site, priority, and setting as factors
    Test = droplevels(factor(Test, levels = test_names, ordered = TRUE)),
    Site = droplevels(factor(Site, levels = city_sites, ordered = TRUE)),
    DashboardPriority = droplevels(factor(DashboardPriority,
                                          levels = dashboard_priority_order,
                                          ordered = TRUE)),
    DashboardSetting = droplevels(factor(DashboardSetting,
                                         levels = dashboard_pt_setting,
                                         ordered = TRUE)),
    #
    # Determine TAT target for sites with 0 resulted labs
    # Create column concatenating test and priority to determine TAT targets
    Concate1 = paste(Test, DashboardPriority),
    # Create column concatenating test, priority, and setting to determine
    # TAT targets
    Concate2 = paste(Test, DashboardPriority, DashboardSetting),
    # Determine Receive to Result TAT target using this logic:
    # 1. Try to match test, priority, and setting (applicable for labs with
    # different TAT targets based on patient setting and order priority)
    # 2. Try to match test and priority (applicable for labs with different
    # TAT targets based on order priority)
    # 3. Try to match test - this is for tests with (applicable for labs with
    # TAT targets that are independent of patient setting or priority)
    #
    # Determine Receive to Result TAT target based on above logic/scenarios
    ReceiveResultTarget =
      # If TAT target is known, keep TAT target
      ifelse(!is.na(ReceiveResultTarget), ReceiveResultTarget,
             # Try to match on scenario 1
             ifelse(
               !is.na(match(Concate2, tat_targets$Concate)),
               tat_targets$ReceiveToResultTarget[
                 match(Concate2, tat_targets$Concate)],
               # Try to match on scenario 2
               ifelse(
                 !is.na(match(Concate1, tat_targets$Concate)),
                 tat_targets$ReceiveToResultTarget[
                   match(Concate1, tat_targets$Concate)],
                 # Try to match on scenario 3
                 tat_targets$ReceiveToResultTarget[
                   match(Test, tat_targets$Concate)]))),
    #
    # Determine Collect to Result TAT target based on above logic/scenarios
    # Determine Receive to Result TAT target based on above logic/scenarios
    CollectResultTarget =
      # If TAT target is known, keep TAT target
      ifelse(!is.na(CollectResultTarget), CollectResultTarget,
             # Try to match on scenario 1
             ifelse(
               !is.na(match(Concate2, tat_targets$Concate)),
               tat_targets$CollectToResultTarget[
                 match(Concate2, tat_targets$Concate)],
               # Try to match on scenario 2
               ifelse(
                 !is.na(match(Concate1, tat_targets$Concate)),
                 tat_targets$CollectToResultTarget[
                   match(Concate1, tat_targets$Concate)],
                 # Try to match on scenario 3
                 tat_targets$CollectToResultTarget[
                   match(Test, tat_targets$Concate)]))),
    #
    # Format target TAT for tables from numbers to "<=X min"
    ReceiveResultTarget = paste0("<=", ReceiveResultTarget, " min"),
    CollectResultTarget = paste0("<=", CollectResultTarget, " min"),
    #
    # Format percentage of labs in target
    ReceiveResultPercent = percent(ReceiveResultPercent, digits = 0),
    CollectResultPercent = percent(CollectResultPercent, digits = 0),
    #
    # Create a new column with test and priority to be used in tables later
    TestAndPriority = paste(Test, "-", DashboardPriority),
    #
    # Apply conditional color formatting to TAT percentages based on status 
    # definitions for each lab division
    ReceiveResultPercent = cell_spec(
      ReceiveResultPercent, "html",
      color = ifelse(is.na(ReceiveResultPercent), "lightgray",
                     ifelse(
                       (ReceiveResultPercent >= 0.95 &
                          Division %in% c("Chemistry", "Hematology")) |
                         (ReceiveResultPercent == 1.00 &
                            Division %in% c("Microbiology RRL")),
                       "green",
                       ifelse(
                         (ReceiveResultPercent >= 0.8 &
                            ReceiveResultPercent < 0.95 &
                            Division %in% c("Chemistry", "Hematology")) |
                           (ReceiveResultPercent >= 0.9 &
                              ReceiveResultPercent < 1.0 &
                              Division %in% c("Microbiology RRL")),
                         "orange", "red")))),
    CollectResultPercent = cell_spec(
      CollectResultPercent, "html",
      color = ifelse(is.na(CollectResultPercent), "lightgray",
                     ifelse(
                       (CollectResultPercent >= 0.95 &
                          Division %in% c("Chemistry", "Hematology")) |
                         (CollectResultPercent == 1.00 &
                            Division %in% c("Microbiology RRL")),
                       "green",
                       ifelse(
                         (CollectResultPercent >= 0.8 &
                            CollectResultPercent < 0.95 &
                            Division %in% c("Chemistry", "Hematology")) |
                           (CollectResultPercent >= 0.9 &
                              CollectResultPercent < 1.0 &
                              Division %in% c("Microbiology RRL")),
                         "orange", "red")))),
    #
    # Remove concatenated columns used for matching
    Concate1 = NULL,
    Concate2 = NULL,
    #
    # Create new column with test and priority to be used in tables later
    TestAndPriority = paste(Test, "-", DashboardPriority, "Labs"),
    #
    # Apply conditional formatting to TAT percentages based on status
    # definitions for each lab division
    #
    # Chemistry & Hematology:
    # Green: >= 95%, Yellow: >= 80% & < 95%, Red: < 80%
    # Microbiology:
    # Green: 100%, Yellow: >= 90% & < 100%, Red: < 90%
    #
    # Receive to Result Percent
    ReceiveResultPercent = cell_spec(
      ReceiveResultPercent, "html",
      color = ifelse(is.na(ReceiveResultPercent), "lightgray",
                     ifelse((ReceiveResultPercent >= 0.95 &
                               (Division %in% c("Chemistry",
                                                   "Hematology"))) |
                              (ReceiveResultPercent == 1.00 &
                                 Division %in% c("Microbiology RRL")),
                            "green",
                            ifelse((ReceiveResultPercent >=0.8 &
                                      ReceiveResultPercent < 0.95 &
                                      (Division %in% c("Chemistry",
                                                          "Hematology"))) |
                                     (ReceiveResultPercent >= 0.90 &
                                        ReceiveResultPercent < 1.0 &
                                        Division %in% c("Microbiology RRL")),
                                   "orange", "red")))),
    #
    # Collect to Result Percent
    CollectResultPercent = cell_spec(
      CollectResultPercent, "html",
      color = ifelse(is.na(CollectResultPercent), "lightgray",
                     ifelse((CollectResultPercent >= 0.95 &
                               Division %in% c("Chemistry",
                                                  "Hematology")) |
                              (CollectResultPercent == 1.00 &
                                 Division %in% c("Microbiology RRL")),
                            "green",
                            ifelse((CollectResultPercent >=0.8 &
                                      CollectResultPercent < 0.95 &
                                      Division %in% c("Chemistry",
                                                         "Hematology")) |
                                     (CollectResultPercent >= 0.90 &
                                        CollectResultPercent < 1.0 &
                                        Division %in% c("Microbiology RRL")),
                                   "orange", "red"))))) %>%
  arrange(Test, Site, DashboardPriority, DashboardSetting)
# 
# Melt summarized data into a long dataframe
lab_dashboard_melt <- melt(lab_summary_test,
                       id.var = c("Test",
                                  "Site",
                                  "DashboardPriority",
                                  "TestAndPriority",
                                  "DashboardSetting",
                                  "ReceiveResultTarget",
                                  "CollectResultTarget"),
                       measure.vars = c("ReceiveResultPercent",
                                        "CollectResultPercent"))
#
# Cast dataframe into wide format for use in tables later
lab_dashboard_cast <- dcast(lab_dashboard_melt,
                            Test +
                              DashboardPriority +
                              TestAndPriority +
                              DashboardSetting +
                              ReceiveResultTarget +
                              CollectResultTarget ~
                              variable +
                              Site,
                            value.var = "value")
#
# Rearrange casted dataframe columns based on desired table aesthetics
lab_dashboard_cast_1 <- lab_dashboard_cast[ , c(1:3, 5, 4, 7:12, 6, 4, 13:18)]

lab_dashboard_cast_2 <- lab_dashboard_cast %>%
  mutate(DashboardSetting2 = DashboardSetting) %>%
  select(Test, DashboardPriority, TestAndPriority,
         ReceiveResultTarget, DashboardSetting,
         ReceiveResultPercent_MSH, ReceiveResultPercent_MSQ,
         ReceiveResultPercent_MSBI, ReceiveResultPercent_MSB,
         ReceiveResultPercent_MSW, ReceiveResultPercent_MSM,
         CollectResultTarget, DashboardSetting2,
         CollectResultPercent_MSH, CollectResultPercent_MSQ,
         CollectResultPercent_MSBI, CollectResultPercent_MSB,
         CollectResultPercent_MSW, CollectResultPercent_MSM)


# Save outputs in a list
# lab_sub_output <- list(lab_df, lab_summary, lab_dashboard1, lab_dashboard2)
# lab_sub_output

```

```{r Code for making kable}
lab_kable <- lab_dashboard_cast_2[ , c(3:ncol(lab_dashboard_cast_2))]

kable(lab_kable, format = "html", escape = FALSE, align = "c",
      col.names = c("Test & Priority",
                    "Target", "Setting",
                    "MSH", "MSQ", "MSBI", "MSB", "MSW", "MSM",
                    "Target", "Setting",
                    "MSH", "MSQ", "MSBI", "MSB", "MSW", "MSM")) %>%
  kable_styling(bootstrap_options = "hover", position = "center",
                font_size = 11) %>%
  column_spec(column = c(1, 9, 17), border_right = "thin solid lightgray") %>%
  add_header_above(c(" ",
                     "Receive to Result Within Target" = (ncol(lab_kable)-1)/2,
                     "Collect to Result Within Target" = (ncol(lab_kable)-1)/2),
                   background = c("white", "#00AEEF", "#221f72"),
                   color = "white", line = FALSE, font_size = 13) %>%
  column_spec(column = 2:9, background = "#E6F8FF", color = "black") %>%
  column_spec(column = 10:17, background = "#EBEBF9", color = "black") %>%
  #column_spec(column = 2:17, background = "inherit", color = "inherit") %>%
  column_spec(column = 1, width_min = "125px") %>%
  column_spec(column = c(3, 11), width_min = "100px") %>%
  row_spec(row = 0, font_size = 13) %>%
  collapse_rows(columns = c(1, 2, 10))


```



```{r Subset and format SCC and Sunquest data for each lab division weekday dashboard, warning = FALSE, message = FALSE, echo = FALSE}

# Chemistry
chem_sub_output <-lab_sub_summarize(scc_sun_wday_master, LabDivision = "Chemistry")
chem_subset <- chem_sub_output[[1]]
chemistry_summary <- chem_sub_output[[2]]
chemistry_dashboard1 <- chem_sub_output[[3]]
chemistry_dashboard2 <- chem_sub_output[[4]]

# Chemistry: Manually remove unused combinations
chemistry_dashboard2 <- chemistry_dashboard2[!(((chemistry_dashboard2$Test == "Troponin" | chemistry_dashboard2$Test == "Lactate WB") & (chemistry_dashboard2$DashboardPriority != "All" | chemistry_dashboard2$DashboardSetting == "Amb")) | (chemistry_dashboard2$Test == "BUN" & chemistry_dashboard2$DashboardPriority == "All")), ]
row.names(chemistry_dashboard2) <- 1:nrow(chemistry_dashboard2)

chem_table <- chemistry_dashboard2[ , 3:ncol(chemistry_dashboard2)]

# Hematology
hem_sub_output <-lab_sub_summarize(scc_sun_wday_master, LabDivision = "Hematology")
hem_subset <- hem_sub_output[[1]]
hematology_summary <- hem_sub_output[[2]]
hematology_dashboard1 <- hem_sub_output[[3]]
hematology_dashboard2 <- hem_sub_output[[4]]

hem_table<- hematology_dashboard2[ , 3:ncol(hematology_dashboard2)]

# Microbiology RRL
micro_sub_output <-lab_sub_summarize(scc_sun_wday_master, LabDivision = "Microbiology RRL")
micro_subset <- micro_sub_output[[1]]
micro_summary <- micro_sub_output[[2]]
micro_dashboard1 <- micro_sub_output[[3]]
micro_dashboard2 <- micro_sub_output[[4]]

# Microbiology RRL: Manually remove unused combinations
micro_dashboard2 <- micro_dashboard2[!(micro_dashboard2$Test == "C. diff" & micro_dashboard2$DashboardSetting == "Amb"), ]
row.names(micro_dashboard2) <- 1:nrow(micro_dashboard2)

micro_table <- micro_dashboard2[ , 3:ncol(micro_dashboard2)]
```




















