---
title: "Laboratory Efficiency Indicators: 30 Day Lookback"
date: "2/24/2020"
output: html_document
---

<h2><span style="color: red;">Draft - Not for Distribution</span></h2>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Install and load packages, echo = FALSE, warning = FALSE, message = FALSE}
# install.packages("gridExtra")
# install.packages("scales")

library(timeDate)
library(readxl)
library(bizdays)
library(dplyr)
library(lubridate)
library(reshape2)
library(knitr)
library(kableExtra)
library(formattable)
library(rmarkdown)
library(stringr)
library(writexl)
library(ggplot2)
library(gridExtra)
library(scales)
```

```{r Clear history and import relevant data, echo = FALSE, warning = FALSE, message = FALSE}
rm(list = ls())

user_wd <- "J:\\Presidents\\HSPI-PM\\Operations Analytics and Optimization\\Projects\\Service Lines\\Lab KPI\\Data\\SCC Sunquest Script Repo"
user_path <- paste0(user_wd, "\\*.*")
setwd(user_wd)

scc_sun_hist <- read_excel(choose.files(default = user_path, caption = "Select Historical Repository"), sheet = 1, col_names = TRUE)

scc_sun_hist$ResultDate <- as.Date(scc_sun_hist$ResultDate, format = "%m/%d/%y")
lookback_period <- 30
start_date <- max(scc_sun_hist$ResultDate) - (lookback_period - 1)

# Orders for labs, sites, patient setting, and priority
cp_micro_lab_order <- c("Troponin", "Lactate WB", "BUN", "HGB", "PT", "Rapid Flu", "C. diff")
site_order <- c("MSH", "MSQ", "MSBI", "MSB", "MSW", "MSSL")
dashboard_pt_setting <- c("ED & ICU", "IP Non-ICU", "Amb")
dashboard_priority_order <- c("All", "Stat", "Routine")

mshs_colors = c("#221f72", "#00AEFF", "#D80B8C", "#7f7f7f")
```

```{r Format historical repository for plotting, echo = FALSE, warning = FALSE, message = FALSE}

dashboard_tat_summary <- scc_sun_hist %>%
  group_by(Site, ResultDate, Division, Test, DashboardPriority, DashboardSetting, ReceiveResultTarget, CollectResultTarget) %>%
  summarize(ResultedVolume = sum(TotalResulted), ResultedVolumeWithTAT = sum(TotalResultedTAT), ReceiveResultInTarget = sum(TotalReceiveResultInTarget), CollectResultInTarget = sum(TotalCollectResultInTarget))

dashboard_tat_summary$ReceiveResultPercent <- dashboard_tat_summary$ReceiveResultInTarget / dashboard_tat_summary$ResultedVolumeWithTAT
dashboard_tat_summary$CollectResultPercent <- dashboard_tat_summary$CollectResultInTarget / dashboard_tat_summary$ResultedVolumeWithTAT
dashboard_tat_summary$ReceiveResultDefectRate <- (dashboard_tat_summary$ResultedVolumeWithTAT - dashboard_tat_summary$ReceiveResultInTarget) / dashboard_tat_summary$ResultedVolumeWithTAT
dashboard_tat_summary$CollectResultDefectRate <- (dashboard_tat_summary$ResultedVolumeWithTAT - dashboard_tat_summary$CollectResultInTarget) / dashboard_tat_summary$ResultedVolumeWithTAT

dashboard_tat_summary$SafeThreshold <- ifelse(dashboard_tat_summary$Test == "Rapid Flu" | dashboard_tat_summary$Test == "C. diff", 1.0, 0.95)
dashboard_tat_summary$NotSafeThreshold <- ifelse(dashboard_tat_summary$Test == "Rapid Flu" | dashboard_tat_summary$Test == "C. diff", 0.9, 0.8)

# Summarize volume data
# dashboard_vol_summary <- scc_sun_hist %>%
#   group_by(Site, ResultDate, Test) %>%
#   summarize(ResultedVolume = sum(TotalResulted))

dashboard_vol_summary <- scc_sun_hist %>%
  group_by(Site, ResultDate, Test, DashboardPriority) %>%
  summarize(ResultedVolume = sum(TotalResulted))

```

```{r Test plot, echo = FALSE, warning = FALSE, message = FALSE}

troponin_test <- dashboard_tat_summary[dashboard_tat_summary$Test == "Troponin", ]
troponin_test <- troponin_test[troponin_test$DashboardSetting == "ED & ICU" | troponin_test$DashboardSetting == "IP Non-ICU", ]

troponin_test$ResultDate <- as.Date(troponin_test$ResultDate, format = "%m/%d/%y")

trop_vol <- dashboard_vol_summary[dashboard_vol_summary$Test == "Troponin" & dashboard_vol_summary$Site == "MSH", ]

base10 <- floor(log10(max(trop_vol$ResultedVolume[trop_vol$ResultDate >= start_date])))
scale <- ceiling(max(trop_vol$ResultedVolume[trop_vol$ResultDate >= start_date])/(10^(base10-1)))*10^(base10-1)

ggplot() +
  # Plot safe, at risk, not safe thresholds
  geom_rect(aes(xmin = start_date - 1, xmax = max(troponin_test$ResultDate) + 1, ymin = -Inf, ymax = min(troponin_test$NotSafeThreshold), fill = "Not Safe", alpha = "Not Safe")) +
  geom_rect(aes(xmin = start_date - 1, xmax = max(troponin_test$ResultDate) + 1, ymin = min(troponin_test$NotSafeThreshold), ymax = min(troponin_test$SafeThreshold), fill = "At Risk", alpha = "At Risk")) +
  geom_rect(aes(xmin = start_date - 1, xmax = max(troponin_test$ResultDate) + 1, ymin = min(troponin_test$SafeThreshold), ymax = Inf, fill = "Safe", alpha = "Safe")) +
  # Plot turnaround time percentages
  geom_point(data = troponin_test[troponin_test$ResultDate >= start_date & troponin_test$Site == "MSH", ], aes(x = ResultDate, y = ReceiveResultPercent, color = DashboardSetting, shape = DashboardSetting), size = 3) +
  geom_line(data = troponin_test[troponin_test$ResultDate >= start_date & troponin_test$Site == "MSH", ], aes(x = ResultDate, y = ReceiveResultPercent, color = DashboardSetting), linetype = "dashed") +
  # Plot resulted volume on secondary axis
  geom_point(data = trop_vol, aes(x = ResultDate, y = ResultedVolume/scale, size = "Volume"), color = "#959595", shape = 18) +
  geom_line(data = trop_vol, aes(x = ResultDate, y = ResultedVolume/scale, linetype = "Volume"), color = "#959595") +
  # Format graph
  labs(title = "MSH Troponin Percentage of Labs within Target TAT:\n Receive to Result", x = "Date",  y = "Percentage of Labs", shape = "Setting") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "right", legend.box = "vertical", legend.title = element_text(size = 10), legend.text = element_text(size = 8),axis.text.x = element_text(angle = 30, hjust = 1)) +
  scale_x_date(limits = c(start_date -1, max(troponin_test$ResultDate)+1), breaks = seq(start_date, max(troponin_test$ResultDate), by = 3), date_minor_breaks = "1 day", date_labels = "%m/%d/%y", expand = c(0, 0, 0, 0)) +
  scale_size_manual(name = "Resulted Volume", values = 2, labels = "All Settings") + 
  scale_linetype_manual(name = "Resulted Volume", values = "dashed", labels = "All Settings") +
  scale_fill_manual(name = "Status", values = c("Not Safe" = "red", "At Risk" = "orange", "Safe" = "green"), labels=c("Not Safe","At Risk","Safe")) +
  scale_alpha_manual(name = "Status", values = c("Not Safe" = 0.2, "At Risk" = 0.2, "Safe" = 0.2), labels=c("Not Safe","At Risk","Safe")) +
  scale_color_manual(name = "Setting", values = mshs_colors) +
  guides(color = guide_legend(order = 1), shape = guide_legend(order = 1), fill = guide_legend(order = 3), alpha = guide_legend(order = 3), size = guide_legend(order = 2), linetype = guide_legend(order = 2)) +
  scale_y_continuous(limits = c(NA, 1), labels = percent_format(accuracy = 1), expand = c(0,0, .05, 0), sec.axis = sec_axis(~.*scale, name = "Volume of Labs"))

```

```{r Test function for TAT percentage graphs, echo = FALSE, warning = FALSE, message = FALSE}

# Create a custom function for graphing percentage of labs within TAT target
# tat_percentage_graph <- function(data, site, metric) {
#   metric_name <- ifelse(metric == "ReceiveResultPercent", "Receive to Result TAT", ifelse(metric == "CollectResultPercent", "Collect to Result TAT", "Error"))
#   ggplot() +
#     geom_rect(aes(xmin = start_date - 1, xmax = max(data$ResultDate) + 1, ymin = -Inf, ymax = min(data$NotSafeThreshold), fill = "Not Safe", alpha = "Not Safe")) +
#     geom_rect(aes(xmin = start_date - 1, xmax = max(data$ResultDate) + 1, ymin = min(data$NotSafeThreshold), ymax = min(data$SafeThreshold), fill = "At Risk", alpha = "At Risk")) +
#     geom_rect(aes(xmin = start_date - 1, xmax = max(data$ResultDate) + 1, ymin = min(data$SafeThreshold), ymax = Inf, fill = "Safe", alpha = "Safe")) +
#     geom_point(data = data[data$ResultDate >= start_date & data$Site == site, ], aes_string(x = "ResultDate", y = metric, color = "DashboardSetting", shape = "DashboardSetting"), size = 3) +
#     geom_line(data = data[data$ResultDate >= start_date & data$Site == site, ], aes_string(x = "ResultDate", y = metric, color = "DashboardSetting"), linetype = "dashed") +
#     labs(title = paste0("Troponin ", metric_name, ":\n", site, " Percentage of Labs within Target"), x = "Date",  y = "Percentage of Labs", color = "Setting", shape = "Setting") +
#     theme_bw() +
#     theme(plot.title = element_text(hjust = 0.5), legend.position = "right", legend.box = "vertical", legend.title = element_text(size = 10), legend.text = element_text(size = 8),axis.text.x = element_text(angle = 30, hjust = 1)) +
#     scale_x_date(limits = c(start_date -1, max(data$ResultDate)+1), breaks = seq(start_date, max(data$ResultDate), by = 3), date_minor_breaks = "1 day", date_labels = "%m/%d/%y", expand = c(0, 0, 0, 0)) +
#     scale_fill_manual(name = "Status", values = c("Not Safe" = "red", "At Risk" = "orange", "Safe" = "green"), breaks=c("Not Safe","At Risk","Safe")) + 
#     scale_alpha_manual(name = "Status", values = c("Not Safe" = 0.2, "At Risk" = 0.2, "Safe" = 0.2), breaks=c("Not Safe","At Risk","Safe")) +
#     scale_color_manual(name = "Setting", values = mshs_colors)
# }

# tat_percentage_graph(troponin_test, "MSH", metric = "ReceiveResultPercent")
```

```{r Filter unused TAT combinations, echo = FALSE, warning = FALSE, message = FALSE}
# Manually remove patient settings or combinations not represented in efficiency indicator dashboards
dashboard_tat_filter <- dashboard_tat_summary
dashboard_tat_filter <- dashboard_tat_filter[!(dashboard_tat_filter$DashboardPriority == "Other" | dashboard_tat_filter$DashboardSetting == "Other" |
                                                             ((dashboard_tat_filter$Test == "Troponin" | dashboard_tat_filter$Test == "Lactate WB") & dashboard_tat_filter$DashboardSetting == "Amb") |
                                                             (dashboard_tat_filter$Test == "C. diff" & dashboard_tat_filter$DashboardSetting == "Amb")), ]

dashboard_tat_filter$Site <- factor(dashboard_tat_filter$Site, levels = site_order)
dashboard_tat_filter$Test <- factor(dashboard_tat_filter$Test, levels = cp_micro_lab_order)
dashboard_tat_filter$DashboardPriority <- factor(dashboard_tat_filter$DashboardPriority, levels = dashboard_priority_order)
dashboard_tat_filter$DashboardSetting <- factor(dashboard_tat_filter$DashboardSetting, levels = dashboard_pt_setting)
dashboard_tat_filter <- dashboard_tat_filter[order(dashboard_tat_filter$Test, dashboard_tat_filter$Site, dashboard_tat_filter$DashboardPriority, dashboard_tat_filter$DashboardSetting, dashboard_tat_filter$ResultDate), ]
```

```{r Custom function for graphing TAT percentage, echo = FALSE, warning = FALSE, message = FALSE}
tat_percentage_graph <- function(data, test_name, site_name, lab_priority, metric) {
  metric_name <- ifelse(metric == "ReceiveResultPercent", "Receive to Result TAT", ifelse(metric == "CollectResultPercent", "Collect to Result TAT", "Error"))
  # df <- data[data$ResultDate >= start_date & data$Test == test & data$Site == site & data$DashboardPriority == lab_priority, ]
  # 
  ggplot() +
    geom_rect(aes(xmin = start_date - 1, xmax = max(data$ResultDate) + 1, ymin = -Inf, ymax = min(data$NotSafeThreshold), fill = "Not Safe", alpha = "Not Safe")) +
    geom_rect(aes(xmin = start_date - 1, xmax = max(data$ResultDate) + 1, ymin = min(data$NotSafeThreshold), ymax = min(data$SafeThreshold), fill = "At Risk", alpha = "At Risk")) +
    geom_rect(aes(xmin = start_date - 1, xmax = max(data$ResultDate) + 1, ymin = min(data$SafeThreshold), ymax = Inf, fill = "Safe", alpha = "Safe")) +
    geom_point(data = data[data$ResultDate >= start_date & data$Test == test_name & data$Site == site_name & data$DashboardPriority == lab_priority, ], aes_string(x = "ResultDate", y = metric, color = "DashboardSetting", shape = "DashboardSetting"), size = 3) +
    geom_line(data = data[data$ResultDate >= start_date & data$Test == test_name & data$Site == site_name & data$DashboardPriority == lab_priority, ], aes_string(x = "ResultDate", y = metric, color = "DashboardSetting"), linetype = "dashed") +
    labs(title = paste0(test_name, " ", metric_name, ":\n", site_name, " Percentage of ", lab_priority, " Labs within Target"), x = "Date",  y = "Percentage of Labs", color = "Setting", shape = "Setting") +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5), legend.position = "right", legend.box = "vertical", legend.title = element_text(size = 10), legend.text = element_text(size = 8),axis.text.x = element_text(angle = 30, hjust = 1)) +
    scale_x_date(limits = c(start_date -1, max(data$ResultDate)+1), breaks = seq(start_date, max(data$ResultDate), by = 3), date_minor_breaks = "1 day", date_labels = "%m/%d/%y", expand = c(0, 0, 0, 0)) +
    scale_fill_manual(name = "Status", values = c("Not Safe" = "red", "At Risk" = "orange", "Safe" = "green"), breaks=c("Not Safe","At Risk","Safe")) +
    scale_alpha_manual(name = "Status", values = c("Not Safe" = 0.15, "At Risk" = 0.15, "Safe" = 0.15), breaks=c("Not Safe","At Risk","Safe")) +
    scale_color_manual(name = "Setting", values = mshs_colors)
}


# Custom function for plotting total resulted lab volume
# resulted_volume_graph <- function(data, test_name, site_name) {
#   ggplot() +
#     geom_point(data = data[data$ResultDate >= start_date & data$Test == test_name & data$Site == site_name, ], aes(x = ResultDate, y = ResultedVolume, color = "All Settings"), shape = 16, size = 3) +
#     geom_line(data = data[data$ResultDate >= start_date & data$Test == test_name & data$Site == site_name, ], aes(x = ResultDate, y = ResultedVolume, color = "All Settings"), linetype = "dashed") +
#     labs(title = paste0(site_name, ": ", test_name, " Resulted Lab Volume"), x = "Date",  y = "Volume of Labs") +
#     theme_bw() +
#     theme(plot.title = element_text(hjust = 0.5), legend.position = "right", legend.box = "vertical", legend.title = element_text(size = 10), legend.text = element_text(size = 8),axis.text.x = element_text(angle = 30, hjust = 1)) +
#     scale_x_date(limits = c(start_date -1, max(data$ResultDate)+1), breaks = seq(start_date, max(data$ResultDate), by = 3), date_minor_breaks = "1 day", date_labels = "%m/%d/%y", expand = c(0, 0, 0, 0)) +
#     scale_color_manual(name = "All Settings", values = mshs_colors)
# }

# Function for plotting total resulted lab volume stratified by order priority
resulted_volume_graph <- function(data, test_name, site_name) {
  ggplot() +
    geom_point(data = data[data$ResultDate >= start_date & data$Test == test_name & data$Site == site_name, ], aes(x = ResultDate, y = ResultedVolume, color = DashboardPriority, shape = DashboardPriority), size = 3) +
    geom_line(data = data[data$ResultDate >= start_date & data$Test == test_name & data$Site == site_name, ], aes(x = ResultDate, y = ResultedVolume, color = DashboardPriority), linetype = "dashed") +
    labs(title = paste0(site_name, ": ", test_name, " Resulted Lab Volume"), x = "Date",  y = "Volume of Labs", color = "Priority", shape = "Priority") +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5), legend.position = "right", legend.box = "vertical", legend.title = element_text(size = 10), legend.text = element_text(size = 8),axis.text.x = element_text(angle = 30, hjust = 1)) +
    scale_x_date(limits = c(start_date -1, max(data$ResultDate)+1), breaks = seq(start_date, max(data$ResultDate), by = 3), date_minor_breaks = "1 day", date_labels = "%m/%d/%y", expand = c(0, 0, 0, 0)) +
    scale_color_manual(name = "Priority", values = mshs_colors)
}
```

```{r Create new custom function for graphing TAT percentages within target and resulted lab volume on a secondary axis, echo = FALSE, warning = FALSE, message = FALSE, fig.height = 4, fig.width = 8}

test_name <- "HGB"
site_name <- "MSH"
lab_priority <- "Routine"
metric <- "ReceiveResultPercent"

data <- dashboard_tat_filter
data_tat_plot <- data[data$ResultDate >= start_date & data$Test == test_name & data$Site == site_name & data$DashboardPriority == lab_priority, ] 


data_vol <- dashboard_vol_summary
data_vol_plot <- data_vol[data_vol$ResultDate >= start_date & data_vol$Test == test_name & data_vol$Site == site_name & data_vol$DashboardPriority == lab_priority, ]

min_vol <- min(data_vol_plot$ResultedVolume)
max_vol <- max(data_vol_plot$ResultedVolume)

min_tat <- min(data_tat_plot[ , colnames(data_tat_plot) == metric])
max_tat <- max(data_tat_plot[ , colnames(data_tat_plot) == metric])

base10 <- floor(log10(max(data_vol_plot$ResultedVolume)))

scale <- ceiling(max(data_vol_plot$ResultedVolume)/(10^(base10-1)))*10^(base10-1)
# scale <- max(data_vol_plot$ResultedVolume)

# min_ratio  <- min(data_vol_plot$ResultedVolume)/min(data_tat_plot$ReceiveResultPercent)
# max_ratio  <- max(data_vol_plot$ResultedVolume)/max(data_tat_plot$ReceiveResultPercent)
# scale <- mean(c(max_ratio, min_ratio))

metric_name <- ifelse(metric == "ReceiveResultPercent", "Receive to Result", ifelse(metric == "CollectResultPercent", "Collect to Result", "Error"))

ggplot() +
  # Plot safe, at risk, not safe thresholds
  geom_rect(aes(xmin = start_date - 1, xmax = max(data_tat_plot$ResultDate) + 1, ymin = -Inf, ymax = min(data_tat_plot$NotSafeThreshold), fill = "Not Safe", alpha = "Not Safe")) +
  geom_rect(aes(xmin = start_date - 1, xmax = max(data_tat_plot$ResultDate) + 1, ymin = min(data_tat_plot$NotSafeThreshold), ymax = min(data_tat_plot$SafeThreshold), fill = "At Risk", alpha = "At Risk"), show.legend = FALSE) +
  geom_rect(aes(xmin = start_date - 1, xmax = max(data_tat_plot$ResultDate) + 1, ymin = min(data_tat_plot$SafeThreshold), ymax = 1, fill = "Safe", alpha = "Safe"), show.legend = FALSE) + 
  geom_rect(aes(xmin = start_date - 1, xmax = max(data_tat_plot$ResultDate) + 1, ymin = 1, ymax = Inf, fill = "N/A", alpha = "N/A"), show.legend = FALSE) +
  # Plot percentage of labs within turnaround time target
  geom_point(data = data_tat_plot, aes_string(x = "ResultDate", y = metric, color = "DashboardSetting", shape = "DashboardSetting"), size = 3) +
  geom_line(data = data_tat_plot, aes_string(x = "ResultDate", y = metric, color = "DashboardSetting"), linetype = "dashed") +
  # Plot resulted volume on secondary axis
  geom_point(data = data_vol_plot, aes(x = ResultDate, y = ResultedVolume/scale, size = "Volume"), color = "#959595", shape = 18) +
  geom_line(data = data_vol_plot, aes(x = ResultDate, y = ResultedVolume/scale, linetype = "Volume"), color = "#959595") +
  #
  labs(title = paste0(site_name, " ", test_name, " ", metric_name, ":\n", "Percentage of ", lab_priority, " Labs within Target TAT"), x = "Date",  y = "Percentage of Labs", color = "Setting", shape = "Setting", fill = "Status", alpha = "Status", linetype = "Resulted Volume", size = "Resulted Volume") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "right", legend.box = "vertical", legend.title = element_text(size = 10), legend.text = element_text(size = 8),axis.text.x = element_text(angle = 30, hjust = 1)) +
  scale_x_date(limits = c(start_date -1, max(data_tat_plot$ResultDate)+1), breaks = seq(start_date, max(data_tat_plot$ResultDate), by = 3), date_minor_breaks = "1 day", date_labels = "%m/%d/%y", expand = c(0, 0, 0, 0)) +
  scale_fill_manual(name = "Status", values = c("Not Safe" = "red", "At Risk" = "orange", "Safe" = "green", "N/A" = "grey"), breaks=c("Not Safe","At Risk","Safe")) +
  scale_alpha_manual(name = "Status", values = c("Not Safe" = 0.25, "At Risk" = 0.25, "Safe" = 0.25, "N/A" = 0.5), breaks=c("Not Safe","At Risk","Safe")) +
  scale_color_manual(name = "Setting", values = mshs_colors) +
  scale_size_manual(name = "Resulted Volume", values = 2, labels = paste(lab_priority, "Labs, \n All Settings")) + 
  scale_linetype_manual(name = "Resulted Volume", values = "dotted", labels = paste(lab_priority, "Labs, \n All Settings")) +
  guides(color = guide_legend(order = 1), shape = guide_legend(order = 1), fill = guide_legend(order = 3), alpha = guide_legend(order = 3), size = guide_legend(order = 2), linetype = guide_legend(order = 2)) +
  scale_y_continuous(limits = c(NA, 1), labels = percent_format(accuracy = 1), sec.axis = sec_axis(~.*scale, name = "Volume of Labs"))

```

```{r Custom function for plotting TAT percentages, resulted volume, and status thresholds, echo = FALSE, warning = FALSE, message = FALSE, fig.height = 4, fig.width = 8}

tat_and_volume_plot <- function(test_name, site_name, lab_priority, metric) {
  # 
  # Subset turnaround time and volume data based on test, site, and priority
  data_tat_plot <- dashboard_tat_filter[dashboard_tat_filter$ResultDate >= start_date & dashboard_tat_filter$Test == test_name & dashboard_tat_filter$Site == site_name & dashboard_tat_filter$DashboardPriority == lab_priority, ]

  data_vol_plot <- dashboard_vol_summary[dashboard_vol_summary$ResultDate >= start_date & dashboard_vol_summary$Test == test_name & dashboard_vol_summary$Site == site_name & dashboard_vol_summary$DashboardPriority == lab_priority, ]
  # 
  # Create printable metric name based on selected metric
  metric_name <- ifelse(metric == "ReceiveResultPercent", "Receive to Result", ifelse(metric == "CollectResultPercent", "Collect to Result", "Error"))
  #
  # Determine scale factor for secondary axis based on maximum resulted volume
  base10 <- floor(log10(max(data_vol_plot$ResultedVolume)))
  scale <- ceiling(max(data_vol_plot$ResultedVolume)/(10^(base10-1)))*10^(base10-1)
  #
  # Create plot and standard settings
  ggplot() +
    # Plot safe, at risk, not safe thresholds
    geom_rect(aes(xmin = start_date - 1, xmax = max(data_tat_plot$ResultDate) + 1, 
                  ymin = -Inf, ymax = min(data_tat_plot$NotSafeThreshold), 
                  fill = "Not Safe", alpha = "Not Safe")) +
    geom_rect(aes(xmin = start_date - 1, xmax = max(data_tat_plot$ResultDate) + 1, 
                  ymin = min(data_tat_plot$NotSafeThreshold), ymax = min(data_tat_plot$SafeThreshold), 
                  fill = "At Risk", alpha = "At Risk"), show.legend = FALSE) +
    geom_rect(aes(xmin = start_date - 1, xmax = max(data_tat_plot$ResultDate) + 1, 
                  ymin = min(data_tat_plot$SafeThreshold), ymax = 1, 
                  fill = "Safe", alpha = "Safe"), show.legend = FALSE) + 
    geom_rect(aes(xmin = start_date - 1, xmax = max(data_tat_plot$ResultDate) + 1, 
                  ymin = 1, ymax = Inf, fill = "N/A", 
                  alpha = "N/A"), show.legend = FALSE) +
    # Plot percentage of labs within turnaround time target
    geom_point(data = data_tat_plot, aes_string(x = "ResultDate", y = metric, color = "DashboardSetting", shape = "DashboardSetting"), size = 3) +
    geom_line(data = data_tat_plot, aes_string(x = "ResultDate", y = metric, color = "DashboardSetting"), linetype = "dashed") +
    # Plot resulted volume on secondary axis
    geom_point(data = data_vol_plot, aes(x = ResultDate, y = ResultedVolume/scale, size = "Volume"), color = "#959595", shape = 18) +
    geom_line(data = data_vol_plot, aes(x = ResultDate, y = ResultedVolume/scale, linetype = "Volume"), color = "#959595") +
    # Specify graph labels and themes
    labs(title = paste0(site_name, " ", test_name, " ", metric_name, ":\n", "Percentage of ", lab_priority, " Labs within Target TAT"), 
         x = "Date",  y = "Percentage of Labs", color = "Setting", shape = "Setting", fill = "Status", alpha = "Status", linetype = "Resulted Volume", size = "Resulted Volume") +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5), legend.position = "right", legend.box = "vertical", 
          legend.title = element_text(size = 10), legend.text = element_text(size = 8),
          axis.text.x = element_text(angle = 30, hjust = 1)) +
    # Specify fills, shapes, and lines mappings and legends
    scale_fill_manual(name = "Status", values = c("Not Safe" = "red", "At Risk" = "orange", "Safe" = "green", "N/A" = "grey"), 
                      breaks=c("Not Safe","At Risk","Safe")) +
    scale_alpha_manual(name = "Status", values = c("Not Safe" = 0.25, "At Risk" = 0.25, "Safe" = 0.25, "N/A" = 0.5), 
                       breaks=c("Not Safe","At Risk","Safe")) +
    scale_color_manual(name = "Setting", values = mshs_colors) +
    scale_size_manual(name = "Resulted Volume", values = 2, labels = paste(lab_priority, "Labs, \n All Settings")) + 
    scale_linetype_manual(name = "Resulted Volume", values = "dotted", labels = paste(lab_priority, "Labs, \n All Settings")) +
    # Reorder legends
    guides(color = guide_legend(order = 1), shape = guide_legend(order = 1), fill = guide_legend(order = 3), alpha = guide_legend(order = 3), 
           size = guide_legend(order = 2), linetype = guide_legend(order = 2)) +
    # Specify axis properties
    scale_x_date(limits = c(start_date -1, max(data_tat_plot$ResultDate)+1), 
                 breaks = seq(start_date, max(data_tat_plot$ResultDate), by = 3), date_minor_breaks = "1 day", 
                 date_labels = "%m/%d/%y", expand = c(0, 0, 0, 0)) +
    scale_y_continuous(limits = c(NA, 1), labels = percent_format(accuracy = 1), 
                       sec.axis = sec_axis(~.*scale, name = "Volume of Labs"))
}



plot_two_tat_graphs <- function(test, site, priority) {
  # Save paramaters as variables for use in plotting function
  test_name <- test
  site_name <- site
  lab_priority <- priority
  #
  # Create plot for receive to result TAT
  receive_result_plot <- tat_and_volume_plot(test_name = test_name, site_name = site_name, lab_priority = lab_priority, metric = "ReceiveResultPercent")
  #
  # Create plot for Collect to Result TAT
  collect_result_plot <- tat_and_volume_plot(test_name = test, site_name = site, lab_priority = priority, metric = "CollectResultPercent")
  #
  # Display plots
  print(receive_result_plot)
  print(collect_result_plot)
  
}

plot_two_tat_graphs(test = "Troponin", site = "MSH", priority = "All")

```

```{r Different methods for iterating through stratifications and plotting, echo = FALSE, warning = FALSE, message = FALSE, fig.height=4, fig.width=8}
test_df <- dashboard_tat_filter[dashboard_tat_filter$Test == "Troponin" | dashboard_tat_filter$Test == "Lactate WB", ]

# tat_percentage_graph2(data = test_df, test_name = "Troponin", site_name = "MSH", lab_priority = "All", metric = "ReceiveResultPercent")

b <- dashboard_tat_filter
for (test in unique(b$Test)) {
  test_df <- b[b$Test == test, ]
  # print(paste("Test:", test))
  sites <- unique(test_df$Site)
  for (site in sites) {
    site_df <- test_df[test_df$Site == site, ]
    # print(paste("Site: ", site))
    priorities <- unique(site_df$DashboardPriority)
    for (priority in priorities) {
      priority_df <- site_df[site_df$DashboardPriority == priority, ]
      # print(paste("Priority: ", priority))
      # print(paste(test, site, priority))
      # print(head(new_test4, 10))
      # print(tat_percentage_graph(data = priority_df, test_name = test, site_name = site, lab_priority = priority, metric = "ReceiveResultPercent"))
      # print(tat_percentage_graph(data = priority_df, test_name = test, site_name = site, lab_priority = priority, metric = "CollectResultPercent"))
    }
    # print(resulted_volume_graph(data = dashboard_vol_summary, test_name = test, site_name = site))
  }
}

```


```{r Custom function for stratifying TAT data, echo = FALSE, warning = FALSE, message = FALSE}
stratified_data_for_plots <- function(tat_data, test) {
  test_df <- tat_data[tat_data$Test == test, ]
  sites <- unique(test_df$Site)
  for (site in sites) {
    site_df <- test_df[test_df$Site == site, ]
    priorities <- unique(site_df$DashboardPriority)
    for (priority in priorities) {
      priority_df <- site_df[site_df$DashboardPriority == priority, ]
      print(tat_percentage_graph(data = priority_df, test_name = test, site_name = site, lab_priority = priority, metric = "ReceiveResultPercent"))
      print(tat_percentage_graph(data = priority_df, test_name = test, site_name = site, lab_priority = priority, metric = "CollectResultPercent"))
      }
    print(resulted_volume_graph(data = dashboard_vol_summary, test_name = test, site_name = site))
  }
}
```


## Percentage of Labs within Target TAT {.tabset}

### Troponin
```{r Troponin historical data, echo = FALSE, warning = FALSE, message = FALSE, fig.height = 4, fig.width = 8, fig.align="center"}
stratified_data_for_plots(tat_data = dashboard_tat_filter, test = "Troponin")
```

### Lactate WB
```{r Lactate WB historical data, echo = FALSE, warning = FALSE, message = FALSE, fig.height = 4, fig.width = 8, fig.align="center"}
stratified_data_for_plots(tat_data = dashboard_tat_filter, test = "Lactate WB")
```

### BUN
```{r BUN historical data, echo = FALSE, warning = FALSE, message = FALSE, fig.height = 4, fig.width = 8, fig.align="center"}
stratified_data_for_plots(tat_data = dashboard_tat_filter, test = "BUN")
```

### HGB
```{r HGB historical data, echo = FALSE, warning = FALSE, message = FALSE, fig.height = 4, fig.width = 8, fig.align="center"}
stratified_data_for_plots(tat_data = dashboard_tat_filter, test = "HGB")
```

### PT
```{r PT historical data, echo = FALSE, warning = FALSE, message = FALSE, fig.height = 4, fig.width = 8, fig.align="center"}
stratified_data_for_plots(tat_data = dashboard_tat_filter, test = "PT")
```

### Rapid Flu
```{r Rapid Flu historical data, echo = FALSE, warning = FALSE, message = FALSE, fig.height = 4, fig.width = 8, fig.align="center"}
stratified_data_for_plots(tat_data = dashboard_tat_filter, test = "Rapid Flu")
```

### C. diff
```{r C. diff historical data, echo = FALSE, warning = FALSE, message = FALSE, fig.height = 4, fig.width = 8, fig.align="center"}
stratified_data_for_plots(tat_data = dashboard_tat_filter, test = "C. diff")
```