---
title: "SCC-and-Sunquest-Control-Charts"
author: "Kate Nevin"
date: "2/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Install and load packages, echo = FALSE, warning = FALSE, message = FALSE}
# install.packages("gridExtra")
# install.packages("ggQC")

library(timeDate)
library(readxl)
library(bizdays)
library(dplyr)
library(lubridate)
library(reshape2)
library(knitr)
library(kableExtra)
library(formattable)
library(rmarkdown)
library(stringr)
library(writexl)
library(ggplot2)
library(gridExtra)
library(ggQC)
```

```{r Clear history and import relevant data, echo = FALSE, warning = FALSE, message = FALSE}
rm(list = ls())

user_wd <- "J:\\Presidents\\HSPI-PM\\Operations Analytics and Optimization\\Projects\\Service Lines\\Lab KPI\\Data\\SCC Sunquest Script Repo"
user_path <- paste0(user_wd, "\\*.*")
setwd(user_wd)

scc_sun_hist <- read_excel(choose.files(default = user_path, caption = "Select Historical Repository"), sheet = 1, col_names = TRUE)

scc_sun_hist$ResultDate <- as.Date(scc_sun_hist$ResultDate, format = "%m/%d/%y")
lookback_period <- 30
start_date <- max(scc_sun_hist$ResultDate) - (lookback_period - 1)

# Orders for labs, sites, patient setting, and priority
cp_micro_lab_order <- c("Troponin", "Lactate WB", "BUN", "HGB", "PT", "Rapid Flu", "C. diff")
site_order <- c("MSH", "MSQ", "MSBI", "MSB", "MSW", "MSSL")
dashboard_pt_setting <- c("ED & ICU", "IP Non-ICU", "Amb")
dashboard_priority_order <- c("All", "Stat", "Routine")

mshs_colors = c("#221f72", "#00AEFF", "#7f7f7f", "#D80B8C")
```

```{r Format historical repository for plotting, echo = FALSE, warning = FALSE, message = FALSE}

dashboard_tat_summary <- scc_sun_hist %>%
  group_by(Site, ResultDate, Division, Test, DashboardPriority, ReceiveResultTarget, CollectResultTarget) %>%
  summarize(ResultedVolume = sum(TotalResulted), ResultedVolumeWithTAT = sum(TotalResultedTAT), ReceiveResultInTarget = sum(TotalReceiveResultInTarget), CollectResultInTarget = sum(TotalCollectResultInTarget))

dashboard_tat_summary$ReceiveResultDefects <- dashboard_tat_summary$ResultedVolumeWithTAT - dashboard_tat_summary$ReceiveResultInTarget
dashboard_tat_summary$CollectResultDefects <- dashboard_tat_summary$ResultedVolumeWithTAT - dashboard_tat_summary$CollectResultInTarget

dashboard_tat_summary$ReceiveResultPercent <- dashboard_tat_summary$ReceiveResultInTarget / dashboard_tat_summary$ResultedVolumeWithTAT
dashboard_tat_summary$CollectResultPercent <- dashboard_tat_summary$CollectResultInTarget / dashboard_tat_summary$ResultedVolumeWithTAT

dashboard_tat_summary$ReceiveResultDefects <- dashboard_tat_summary$ResultedVolumeWithTAT - dashboard_tat_summary$ReceiveResultInTarget
dashboard_tat_summary$CollectResultDefects <- dashboard_tat_summary$ResultedVolumeWithTAT - dashboard_tat_summary$CollectResultInTarget

dashboard_tat_summary$ReceiveResultDefectRate <- dashboard_tat_summary$ReceiveResultDefects / dashboard_tat_summary$ResultedVolumeWithTAT
dashboard_tat_summary$CollectResultDefectRate <- dashboard_tat_summary$CollectResultDefects / dashboard_tat_summary$ResultedVolumeWithTAT

# dashboard_tat_summary$SafeThreshold <- ifelse(dashboard_tat_summary$Test == "Rapid Flu" | dashboard_tat_summary$Test == "C. diff", 1.0, 0.95)
# dashboard_tat_summary$NotSafeThreshold <- ifelse(dashboard_tat_summary$Test == "Rapid Flu" | dashboard_tat_summary$Test == "C. diff", 0.9, 0.8)

# Summarize volume data
# dashboard_vol_summary <- scc_sun_hist %>%
#   group_by(Site, ResultDate, Test) %>%
#   summarize(ResultedVolume = sum(TotalResulted))

dashboard_vol_summary <- scc_sun_hist %>%
  group_by(Site, ResultDate, Test, DashboardPriority) %>%
  summarize(ResultedVolume = sum(TotalResulted))

```

```{r Test plot, echo = FALSE, warning = FALSE, message = FALSE}

troponin_test <- dashboard_tat_summary[dashboard_tat_summary$Test == "Troponin" & dashboard_tat_summary$Site == "MSH" & dashboard_tat_summary$DashboardPriority == "All", ]

center_line <- mean(QC_Lines(data = troponin_test$ReceiveResultDefectRate[troponin_test$ResultDate >= start_date], n = troponin_test$ResultedVolumeWithTAT[troponin_test$ResultDate >= start_date], method = "p")$pBar)

ggplot(data = troponin_test[troponin_test$ResultDate >= start_date, ], aes(x = ResultDate, y = ReceiveResultDefectRate, n = ResultedVolumeWithTAT)) +
  geom_point(color = mshs_colors[1], shape = 16, size = 3) +
  geom_line(color = mshs_colors[1], linetype = "dashed") +
  stat_QC(method = "p", auto.label = T, color.qc_center = "black") +
  labs(title = "MSH Troponin Defect Rate:\n Receive to Result", x = "Date",  y = "Defect Rate") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "right", legend.box = "vertical", legend.title = element_text(size = 10), legend.text = element_text(size = 8),axis.text.x = element_text(angle = 30, hjust = 1)) +
  geom_label(x = max(troponin_test$ResultDate)+1, y = center_line, vjust = 1.2, hjust = 1, label = paste("CL:", round(center_line, digits = 2))) +
  scale_x_date(limits = c(start_date -1, max(troponin_test$ResultDate)+1), breaks = seq(start_date, max(troponin_test$ResultDate), by = 3), date_minor_breaks = "1 day", date_labels = "%m/%d/%y", expand = c(0, 0, 0, 0))

```

```{r Test function for TAT percentage graphs, echo = FALSE, warning = FALSE, message = FALSE}

# Create a custom function for graphing percentage of labs within TAT target
# tat_percentage_graph <- function(data, site, metric) {
#   metric_name <- ifelse(metric == "ReceiveResultPercent", "Receive to Result TAT", ifelse(metric == "CollectResultPercent", "Collect to Result TAT", "Error"))
#   ggplot() +
#     geom_rect(aes(xmin = start_date - 1, xmax = max(data$ResultDate) + 1, ymin = -Inf, ymax = min(data$NotSafeThreshold), fill = "Not Safe", alpha = "Not Safe")) +
#     geom_rect(aes(xmin = start_date - 1, xmax = max(data$ResultDate) + 1, ymin = min(data$NotSafeThreshold), ymax = min(data$SafeThreshold), fill = "At Risk", alpha = "At Risk")) +
#     geom_rect(aes(xmin = start_date - 1, xmax = max(data$ResultDate) + 1, ymin = min(data$SafeThreshold), ymax = Inf, fill = "Safe", alpha = "Safe")) +
#     geom_point(data = data[data$ResultDate >= start_date & data$Site == site, ], aes_string(x = "ResultDate", y = metric, color = "DashboardSetting", shape = "DashboardSetting"), size = 3) +
#     geom_line(data = data[data$ResultDate >= start_date & data$Site == site, ], aes_string(x = "ResultDate", y = metric, color = "DashboardSetting"), linetype = "dashed") +
#     labs(title = paste0("Troponin ", metric_name, ":\n", site, " Percentage of Labs within Target"), x = "Date",  y = "Percentage of Labs", color = "Setting", shape = "Setting") +
#     theme_bw() +
#     theme(plot.title = element_text(hjust = 0.5), legend.position = "right", legend.box = "vertical", legend.title = element_text(size = 10), legend.text = element_text(size = 8),axis.text.x = element_text(angle = 30, hjust = 1)) +
#     scale_x_date(limits = c(start_date -1, max(data$ResultDate)+1), breaks = seq(start_date, max(data$ResultDate), by = 3), date_minor_breaks = "1 day", date_labels = "%m/%d/%y", expand = c(0, 0, 0, 0)) +
#     scale_fill_manual(name = "Status", values = c("Not Safe" = "red", "At Risk" = "orange", "Safe" = "green"), breaks=c("Not Safe","At Risk","Safe")) + 
#     scale_alpha_manual(name = "Status", values = c("Not Safe" = 0.2, "At Risk" = 0.2, "Safe" = 0.2), breaks=c("Not Safe","At Risk","Safe")) +
#     scale_color_manual(name = "Setting", values = mshs_colors)
# }

# tat_percentage_graph(troponin_test, "MSH", metric = "ReceiveResultPercent")
```

```{r Filter unused TAT combinations, echo = FALSE, warning = FALSE, message = FALSE}
# Manually remove patient settings or combinations not represented in efficiency indicator dashboards
dashboard_tat_filter <- dashboard_tat_summary
dashboard_tat_filter <- dashboard_tat_filter[!(dashboard_tat_filter$DashboardPriority == "Other" | dashboard_tat_filter$DashboardSetting == "Other" |
                                                             ((dashboard_tat_filter$Test == "Troponin" | dashboard_tat_filter$Test == "Lactate WB") & dashboard_tat_filter$DashboardSetting == "Amb") |
                                                             (dashboard_tat_filter$Test == "C. diff" & dashboard_tat_filter$DashboardSetting == "Amb")), ]

dashboard_tat_filter$Site <- factor(dashboard_tat_filter$Site, levels = site_order)
dashboard_tat_filter$Test <- factor(dashboard_tat_filter$Test, levels = cp_micro_lab_order)
dashboard_tat_filter$DashboardPriority <- factor(dashboard_tat_filter$DashboardPriority, levels = dashboard_priority_order)
dashboard_tat_filter$DashboardSetting <- factor(dashboard_tat_filter$DashboardSetting, levels = dashboard_pt_setting)
dashboard_tat_filter <- dashboard_tat_filter[order(dashboard_tat_filter$Test, dashboard_tat_filter$Site, dashboard_tat_filter$DashboardPriority, dashboard_tat_filter$DashboardSetting, dashboard_tat_filter$ResultDate), ]
```

```{r Custom function for graphing TAT percentage and resulted lab volume, echo = FALSE, warning = FALSE, message = FALSE}
tat_percentage_graph <- function(data, test_name, site_name, lab_priority, metric) {
  metric_name <- ifelse(metric == "ReceiveResultPercent", "Receive to Result TAT", ifelse(metric == "CollectResultPercent", "Collect to Result TAT", "Error"))
  # df <- data[data$ResultDate >= start_date & data$Test == test & data$Site == site & data$DashboardPriority == lab_priority, ]
  # 
  ggplot() +
    geom_rect(aes(xmin = start_date - 1, xmax = max(data$ResultDate) + 1, ymin = -Inf, ymax = min(data$NotSafeThreshold), fill = "Not Safe", alpha = "Not Safe")) +
    geom_rect(aes(xmin = start_date - 1, xmax = max(data$ResultDate) + 1, ymin = min(data$NotSafeThreshold), ymax = min(data$SafeThreshold), fill = "At Risk", alpha = "At Risk")) +
    geom_rect(aes(xmin = start_date - 1, xmax = max(data$ResultDate) + 1, ymin = min(data$SafeThreshold), ymax = Inf, fill = "Safe", alpha = "Safe")) +
    geom_point(data = data[data$ResultDate >= start_date & data$Test == test_name & data$Site == site_name & data$DashboardPriority == lab_priority, ], aes_string(x = "ResultDate", y = metric, color = "DashboardSetting", shape = "DashboardSetting"), size = 3) +
    geom_line(data = data[data$ResultDate >= start_date & data$Test == test_name & data$Site == site_name & data$DashboardPriority == lab_priority, ], aes_string(x = "ResultDate", y = metric, color = "DashboardSetting"), linetype = "dashed") +
    labs(title = paste0(test_name, " ", metric_name, ":\n", site_name, " Percentage of ", lab_priority, " Labs within Target"), x = "Date",  y = "Percentage of Labs", color = "Setting", shape = "Setting") +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5), legend.position = "right", legend.box = "vertical", legend.title = element_text(size = 10), legend.text = element_text(size = 8),axis.text.x = element_text(angle = 30, hjust = 1)) +
    scale_x_date(limits = c(start_date -1, max(data$ResultDate)+1), breaks = seq(start_date, max(data$ResultDate), by = 3), date_minor_breaks = "1 day", date_labels = "%m/%d/%y", expand = c(0, 0, 0, 0)) +
    scale_fill_manual(name = "Status", values = c("Not Safe" = "red", "At Risk" = "orange", "Safe" = "green"), breaks=c("Not Safe","At Risk","Safe")) +
    scale_alpha_manual(name = "Status", values = c("Not Safe" = 0.15, "At Risk" = 0.15, "Safe" = 0.15), breaks=c("Not Safe","At Risk","Safe")) +
    scale_color_manual(name = "Setting", values = mshs_colors)
}

# Custom function for plotting total resulted lab volume
# resulted_volume_graph <- function(data, test_name, site_name) {
#   ggplot() +
#     geom_point(data = data[data$ResultDate >= start_date & data$Test == test_name & data$Site == site_name, ], aes(x = ResultDate, y = ResultedVolume, color = "All Settings"), shape = 16, size = 3) +
#     geom_line(data = data[data$ResultDate >= start_date & data$Test == test_name & data$Site == site_name, ], aes(x = ResultDate, y = ResultedVolume, color = "All Settings"), linetype = "dashed") +
#     labs(title = paste0(site_name, ": ", test_name, " Resulted Lab Volume"), x = "Date",  y = "Volume of Labs") +
#     theme_bw() +
#     theme(plot.title = element_text(hjust = 0.5), legend.position = "right", legend.box = "vertical", legend.title = element_text(size = 10), legend.text = element_text(size = 8),axis.text.x = element_text(angle = 30, hjust = 1)) +
#     scale_x_date(limits = c(start_date -1, max(data$ResultDate)+1), breaks = seq(start_date, max(data$ResultDate), by = 3), date_minor_breaks = "1 day", date_labels = "%m/%d/%y", expand = c(0, 0, 0, 0)) +
#     scale_color_manual(name = "All Settings", values = mshs_colors)
# }

# Function for plotting total resulted lab volume stratified by order priority
resulted_volume_graph <- function(data, test_name, site_name) {
  ggplot() +
    geom_point(data = data[data$ResultDate >= start_date & data$Test == test_name & data$Site == site_name, ], aes(x = ResultDate, y = ResultedVolume, color = DashboardPriority, shape = DashboardPriority), size = 3) +
    geom_line(data = data[data$ResultDate >= start_date & data$Test == test_name & data$Site == site_name, ], aes(x = ResultDate, y = ResultedVolume, color = DashboardPriority), linetype = "dashed") +
    labs(title = paste0(site_name, ": ", test_name, " Resulted Lab Volume"), x = "Date",  y = "Volume of Labs", color = "Priority", shape = "Priority") +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5), legend.position = "right", legend.box = "vertical", legend.title = element_text(size = 10), legend.text = element_text(size = 8),axis.text.x = element_text(angle = 30, hjust = 1)) +
    scale_x_date(limits = c(start_date -1, max(data$ResultDate)+1), breaks = seq(start_date, max(data$ResultDate), by = 3), date_minor_breaks = "1 day", date_labels = "%m/%d/%y", expand = c(0, 0, 0, 0)) +
    scale_color_manual(name = "Priority", values = mshs_colors)
}
```


```{r Different methods for iterating through stratifications and plotting, echo = FALSE, warning = FALSE, message = FALSE, fig.height=4, fig.width=8}
test_df <- dashboard_tat_filter[dashboard_tat_filter$Test == "Troponin" | dashboard_tat_filter$Test == "Lactate WB", ]

# tat_percentage_graph2(data = test_df, test_name = "Troponin", site_name = "MSH", lab_priority = "All", metric = "ReceiveResultPercent")

b <- dashboard_tat_filter
for (test in unique(b$Test)) {
  test_df <- b[b$Test == test, ]
  # print(paste("Test:", test))
  sites <- unique(test_df$Site)
  for (site in sites) {
    site_df <- test_df[test_df$Site == site, ]
    # print(paste("Site: ", site))
    priorities <- unique(site_df$DashboardPriority)
    for (priority in priorities) {
      priority_df <- site_df[site_df$DashboardPriority == priority, ]
      # print(paste("Priority: ", priority))
      # print(paste(test, site, priority))
      # print(head(new_test4, 10))
      # print(tat_percentage_graph(data = priority_df, test_name = test, site_name = site, lab_priority = priority, metric = "ReceiveResultPercent"))
      # print(tat_percentage_graph(data = priority_df, test_name = test, site_name = site, lab_priority = priority, metric = "CollectResultPercent"))
    }
    # print(resulted_volume_graph(data = dashboard_vol_summary, test_name = test, site_name = site))
  }
}

```


```{r Custom function for stratifying TAT data, echo = FALSE, warning = FALSE, message = FALSE}
# stratified_data_for_plots <- function(tat_data, test) {
#   test_df <- tat_data[tat_data$Test == test, ]
#   sites <- unique(test_df$Site)
#   for (site in sites) {
#     site_df <- test_df[test_df$Site == site, ]
#     priorities <- unique(site_df$DashboardPriority)
#     for (priority in priorities) {
#       priority_df <- site_df[site_df$DashboardPriority == priority, ]
#       print(tat_percentage_graph(data = priority_df, test_name = test, site_name = site, lab_priority = priority, metric = "ReceiveResultPercent"))
#       print(tat_percentage_graph(data = priority_df, test_name = test, site_name = site, lab_priority = priority, metric = "CollectResultPercent"))
#       }
#     print(resulted_volume_graph(data = dashboard_vol_summary, test_name = test, site_name = site))
#   }
# }
```


## Percentage of Labs within Target TAT {.tabset}

### Troponin
```{r Troponin p-chart, echo = FALSE, warning = FALSE, message = FALSE, fig.height = 4, fig.width = 8, fig.align="center"}

```

### Lactate WB
```{r Lactate WB p-chart, echo = FALSE, warning = FALSE, message = FALSE, fig.height = 4, fig.width = 8, fig.align="center"}

```

### BUN
```{r BUN p-chart, echo = FALSE, warning = FALSE, message = FALSE, fig.height = 4, fig.width = 8, fig.align="center"}

```

### HGB
```{r HGB p-chart, echo = FALSE, warning = FALSE, message = FALSE, fig.height = 4, fig.width = 8, fig.align="center"}

```

### PT
```{r PT p-chart, echo = FALSE, warning = FALSE, message = FALSE, fig.height = 4, fig.width = 8, fig.align="center"}

```

### Rapid Flu
```{r Rapid Flu p-chart, echo = FALSE, warning = FALSE, message = FALSE, fig.height = 4, fig.width = 8, fig.align="center"}

```

### C. diff
```{r C. diff p-chart, echo = FALSE, warning = FALSE, message = FALSE, fig.height = 4, fig.width = 8, fig.align="center"}

```